### ISSUE TITLE
Some production errors not appearing in Sentry?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10101]
#10099 didn't appear there... let's investigate!

**Comment by jywarren** [comment]
#10099 should have showed:

```
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] Processing by TagController#show as HTML
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   Parameters: {"id"=>"stormwater"}
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   Rendering layouts/application.html.erb
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   Rendering tag/show.html.erb within layouts/a
pplication
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   Rendered tag/show.html.erb within layouts/ap
plication (8.7ms)
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   Rendered layouts/application.html.erb (9.7ms
)
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] Completed 500 Internal Server Error in 222ms (
ActiveRecord: 89.2ms)
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] ActionView::Template::Error (wrong number of a
rguments (given 0, expected 1)):
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     68: }
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     69: </style>
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     70: 
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     71: <section class="tag-header fdb-block p
b-0" style="<% if @wiki && @wiki.main_image %>background-image: url(<%= @wiki.main_im
age.path %>);<% else %>background: #eee;<% end %>" data-block-type="contents" data-id
="1">
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     72: 
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     73:     <div class="container">
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]     74:         <div class="row text-left just
ify-content-start">
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3]   
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] app/models/image.rb:35:in `path'
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] app/views/tag/show.html.erb:71:in `_app_views_
tag_show_html_erb___4238080608518765667_69880562168780'
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] app/controllers/tag_controller.rb:161:in `bloc
k (2 levels) in show'
[3c5ca7a1-14b5-4e29-89c2-0955c014d6a3] app/controllers/tag_controller.rb:160:in `show
```

**Comment by jywarren** [comment]
The above could be seen as related to https://sentry.io/share/issue/dc7711b4722e4596a5869f8db286bfad/, but actually that is a distinct bug affecting just line 80 of `tag_controller.rb`.
