### ISSUE TITLE
inconsistent Capybara test failures -- debugging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#11161]
Getting this inconsistent test failure - 

```
=====================================[Screenshot]: tmp/screenshots/failures_test_note:_should_not_list_spam_replied_comment_to_registered_user.png
ERROR CommentTest#test_note:_should_not_list_spam_replied_comment_to_registered_user (319.77s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css ".nav-link.loginToggle"
            test/comment_system_tests/comment_test.rb:651:in `block (2 levels) in <class:CommentTest>'
```

@TildaDares in https://github.com/publiclab/plots2/issues/11137#issuecomment-1139540714 : 

> @jywarren The test seems to be passing now but we can still try the suggestion in this article https://medium.com/@yuliaoletskaya/capybara-inconsistent-click-behavior-and-flickering-tests-f50b5fae8ab2

Good idea, opening this in a unique issue to try.

**Comment by jywarren** [comment]
Got another identical one at https://github.com/publiclab/plots2/runs/6884401631?check_suite_focus=true#step:9:134 in https://github.com/publiclab/plots2/pull/11190

```
=====================================[Screenshot]: tmp/screenshots/failures_test_note:_should_not_list_spam_replied_comment_to_registered_user.png
ERROR CommentTest#test_note:_should_not_list_spam_replied_comment_to_registered_user (314.14s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css ".nav-link.loginToggle"
            test/comment_system_tests/comment_test.rb:651:in `block (2 levels) in <class:CommentTest>'
```

**Comment by jywarren** [comment]
```
ERROR CommentTest#test_note:_should_not_list_spam_replied_comment_to_registered_user (337.51s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css ".nav-link.loginToggle"
            test/comment_system_tests/comment_test.rb:651:in `block (2 levels) in <class:CommentTest>'
```

in https://github.com/publiclab/plots2/pull/11255
