### ISSUE TITLE
Fix mysql2 dependency issue

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1498]
There's a problem regarding dependencies for mysql2.

Whenever I run any command (starting with `rake db:setup`), they fail; yielding the following error message: `Gem::LoadError: mysql2 is not part of the bundle. Add it to your Gemfile.`

Here's the trace:

```
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:377:in `block (2 levels) in replace_gem'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `block in require'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/home/ryzokuken/Code/plots2/config/initializers/abstract_mysql2_adapter.rb:1:in `<top (required)>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:245:in `load'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:245:in `block in load'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:245:in `load'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/engine.rb:592:in `each'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/engine.rb:592:in `block in <class:Engine>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `run'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `each'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/application.rb:136:in `initialize!'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ryzokuken/Code/plots2/config/environment.rb:5:in `<top (required)>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `block in require'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/application.rb:103:in `require_environment!'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
```

I realized, that inside `config/environment.rb`, we call: `Plots2::Application.initialize!`. This in turn calls the initializers inside `config/initializers`, one of which is `config/initializers/abstract_mysql2_adapter.rb`.

The body of `config/initializers/abstract_mysql2_adapter.rb`:

```ruby
require 'active_record/connection_adapters/mysql2_adapter'

class ActiveRecord::ConnectionAdapters::Mysql2Adapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

Which I believe depends on the mysql2 gem. I commented out the file temporarily, and the commands worked properly, confirming my hypothesis. All tests passed (@jywarren: Are we really even testing for that particular behavior?), and therefore I am submitting a PR for the time-being while we figure out a real cross-db alternative.

**Comment by ryzokuken** [comment]
@jywarren sorry, a patch for this had already been submitted and this issue was resolved. I was accidentally using an older version of the codebase.
