### ISSUE TITLE
project setup passenger issue

### ISSUE THREAD

**Issue by shelbyfirebaugh** [publiclab/plots2#1503]
hello! i'm brand new to both ruby and open source, so i've run into some problems downloading publiclab locally.

### What happened just before the problem occurred
i've gone through all the setup instructions, but when i run `passenger start` this error appears on localhost:3000:

````
No such file or directory @ rb_sysopen - /Users/Shelby/plots2/config/database.yml (Errno::ENOENT)
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/application/configuration.rb:115:in `read'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/application/configuration.rb:115:in `database_configuration'
  /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.4/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:25:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
  /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.4/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/application.rb:136:in `initialize!'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-3.2.22.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /Users/Shelby/plots2/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in `<main>'
````

i realized that i don't think i actually have passenger installed, so i am working on installing apache2 now. the next step in installation is:
````
Please edit your Apache configuration file, and add these lines:

   LoadModule passenger_module /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.5
     PassengerDefaultRuby /usr/local/Cellar/ruby/2.3.3/bin/ruby
   </IfModule>
````

i've located the apache config file in terminal, but i'm unsure of how to edit it

### PublicLab.org username
shelbyfire

### Browser, version, and operating system
*browser:* chrome version 58.0.3029.110 (64-bit)
*operating system:* OSX 10.10.5

**Comment by shelbyfirebaugh** [comment]
@jywarren here's where i'm at so far! i hope this helps

**Comment by ryzokuken** [comment]
@shelbyfirebaugh try `cp config/database.yml.sqlite.example config/database.yml`

**Comment by ryzokuken** [comment]
If you ran `bundle install --without mysql2 production`, passenger must be installed.

**Comment by shelbyfirebaugh** [comment]
okay, now localhost:3000 looks like this:

<img width="1299" alt="screen shot 2017-07-05 at 18 04 15" src="https://user-images.githubusercontent.com/14167695/27887006-85d4ee6a-61ac-11e7-9423-bed7212b44c1.png">

**Comment by ryzokuken** [comment]
Also do `cp db/schema.rb.example db/schema.rb` and run `rake db:setup` again. That should do the trick.

**Comment by shelbyfirebaugh** [comment]
that worked! thank you so much!

**Comment by ryzokuken** [comment]
@shelbyfirebaugh feel free to hop on our chatroom, using either matrix (https://riot.im/app/#/room/#publiclab:matrix.org), Gitter (https://riot.im/app/#/room/#publiclab:matrix.org) or IRC (chat.publiclab.org) (or #publiclab on OFTC from any IRC client). You are more likely to find help in there :smile:

**Comment by jywarren** [comment]
Many many thanks to @ryzokuken and @shelbyfirebaugh for working through this! Fantastic to see that it was resolved.
