### ISSUE TITLE
New user creation fails on staging due to email notification

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1570]
### What happened just before the problem occurred

I went to http://staging.laboratoriopublico.org/signup and tried to create a new account.

Because staging has no mail server set up, I got an error, and the logs showed:

```
Processing by UsersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"jAuewf43tbci+bgJC+dgxsL72She+0hUuXdleQQhLMM=", "user"=>{"username"=>"warren11", "email"=>"jywarre.n@gmail.com", "pa
ssword"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "drupal_user"=>{"bio"=>""}, "g-recaptcha-response"=>"xxxxxx"}
  Rendered welcome_mailer/add_to_list.text.erb (0.3ms)

Sent mail to publiclaboratory+subscribe@googlegroups.com (10.5ms)
Completed 500 Internal Server Error in 1806.7ms

Errno::ENETUNREACH (Network is unreachable - connect(2) for "localhost" port 25):
  app/mailers/welcome_mailer.rb:11:in `add_to_list'
  app/models/user.rb:134:in `block in add_to_lists'
  app/models/user.rb:133:in `each'
  app/models/user.rb:133:in `add_to_lists'
  app/controllers/users_controller.rb:23:in `create'
```

That's on this line:

`@user.add_to_lists(['publiclaboratory'])`

So, i think it's just because it doesn't have a mailer set up. It goes to this line:

https://github.com/publiclab/plots2/blob/master/app/mailers/welcome_mailer.rb#L11

`    mail(to: list + '+subscribe@googlegroups.com', subject: subject, from: user.email).deliver`

Since this is running in production mode, I don't know of an easy way to deactivate this line for staging. I'm not totally sure why it doesn't seem to cause trouble on commenting, for example, which would also show an error.

It may also be related to #1541? @ryzokuken @icarito 

I'm going to deploy this to master because i think this is an isolated issue that's not going to affect a system with a mailer properly set up. 

****

Just to sum up here, we need to skip the `mail(...)` command if we're on staging if we want to solve this. Reposting the issue to reflect this. The rest of the comments are to an unrelated issue, so i'll make a new one and close this. 

## Possible route forward

This is hard to test before merging to stable, but we could try for:

```ruby
    mail(to: list + '+subscribe@googlegroups.com', subject: subject, from: user.email).try(&:deliver)
```

instead of 

```ruby
    mail(to: list + '+subscribe@googlegroups.com', subject: subject, from: user.email).deliver
```

**Comment by 500swapnil** [comment]
I would like to take up this issue

**Comment by jywarren** [comment]
yes please!

**Comment by 500swapnil** [comment]
I have changed this line 
https://github.com/publiclab/plots2/blob/master/app/mailers/welcome_mailer.rb#L11
Have a look at PR #1613

**Comment by maxtedford** [comment]
Hey @jywarren and @500swapnil, I noticed there's an un-merged PR open for this issue. Do you need any more help?

**Comment by jywarren** [comment]
Hi, @maxtedford -- thanks, I just wasn't sure about if this'd cause silent failures -- see my comment here: https://github.com/publiclab/plots2/pull/1613#issuecomment-329527867

Do you know, or would you like to try to move this forward? We'd appreciate it!

**Comment by ianroberts131** [comment]
I'm taking a look at this now - will let you know if I figure out a way around this

**Comment by ianroberts131** [comment]
So it looks like there is a way to have Rails raise an error if there is a failed delivery with the following:

`config.action_mailer-raise_delivery_errors = true`

Then, maybe we can write a function that rescues and skips the mailer if there is a delivery failure? Something like this:

```
def ignore_exception
  begin
    yield
  rescue Exception
end
```

Then, we can write the code as follows:

```
ignore_exception { mail(to: list + '+subscribe@googlegroups.com', subject: subject, from: user.email).deliver }
```

I'm admittedly not very familiar with exception handling, but intuitively it seems like this could work. Any thoughts?

**Comment by jywarren** [comment]
Oh this looks interesting... but could we activate this all only on staging but not on production? 

But i guess we are seeing a lot of errors due to unsent emails. I wonder if we should just log email sending errors but not display an error to the user? Or could we bump the error to the `flash` and display it but not return a 500 error? I wonder if we could instead of ignoring it, capture and display it.

**Comment by jywarren** [comment]
@icarito can you answer this one? I assume so, but not sure.

**Comment by icarito** [comment]
@namangupta01 yes we have a SMTP service listening locally in port 25 _in production_ - but not in staging container.

I'm thinking we should open the port in the staging container to the docker host port 25 (where we either deliver or drop those messages silently). I'll make a ticket for that. Still it'd be nice if the absence of an SMTP service would be treated gracefully.
