### ISSUE TITLE
Image upload broken on production (urgent)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1576]
### What happened just before the problem occurred

I dragged an image **into the rich editor** at https://publiclab.org/post, and got an error (500).

Other image upload (such as the main image on the /post page, and presumably the legacy editor) works fine.

The logs show:

```
Started POST "/images" for 98.185.61.106 at 2017-08-10 13:26:44 +0000

TypeError (no implicit conversion of nil into Hash):
  rack (1.4.7) lib/rack/request.rb:221:in `merge'
  rack (1.4.7) lib/rack/request.rb:221:in `params'
  rack-openid (1.4.2) lib/rack/openid.rb:92:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.22.4) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.22.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22.4) lib/active_support/callbacks.rb:405:in `_run__2782154395801114568__call__2053670407807515598__callbacks'
  activesupport (3.2.22.4) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.4) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22.4) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.4) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.4) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.4) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22.4) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22.4) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  rack-cache (1.6.1) lib/rack/cache/context.rb:140:in `forward'
  rack-cache (1.6.1) lib/rack/cache/context.rb:147:in `pass'
  rack-cache (1.6.1) lib/rack/cache/context.rb:159:in `invalidate'
  rack-cache (1.6.1) lib/rack/cache/context.rb:74:in `call!'
  rack-cache (1.6.1) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.22.4) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.4) lib/rails/application.rb:231:in `call'
  railties (3.2.22.4) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by jywarren** [comment]
Updates - going to put this aside for a couple hours, unfortunately -- reverting to `v0.2.17` (from .18) on `PublicLab.Editor` did not help. 

Next - try reverting https://github.com/publiclab/plots2/commits ?

**Comment by jywarren** [comment]
Whew, actually reverting to `v0.2.17` DID work -- confirmed just now. SO this is resolved on `plots2` and I will file an issue on PublicLab.Editor: https://github.com/publiclab/PublicLab.Editor/issues/103
