### ISSUE TITLE
Error on adding tag related to tag subscriber email notification

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1769]
https://github.com/publiclab/plots2/blob/348334366f6ccf499a80498e5e06667417f8d764/app/mailers/subscription_mailer.rb#L44

```
Sent mail to AAAAAAAAAA (47.6ms)
Completed 500 Internal Server Error in 413.7ms

Net::SMTPSyntaxError (501 <AAAAAAAAAA>: recipient address must contain a domain
):
  app/mailers/subscription_mailer.rb:44:in `block in notify_tag_added'
  app/mailers/subscription_mailer.rb:41:in `each'
  app/mailers/subscription_mailer.rb:41:in `notify_tag_added'
  app/models/node.rb:677:in `block in add_tag'
  app/models/node.rb:661:in `add_tag'
  app/controllers/tag_controller.rb:167:in `block in create'
  app/controllers/tag_controller.rb:161:in `each'
  app/controllers/tag_controller.rb:161:in `create'
```

**Comment by jywarren** [comment]
This seems to have been due to someone editing their email address manually to something that did not have a domain name -- https://publiclab.org/profile/Tufts_Jumbo to `Tufts_Jumbo` -- don't we validate on profile edit?

**Comment by jywarren** [comment]
OK, writing tests for this.

**Comment by jywarren** [comment]
working on this in https://github.com/publiclab/plots2/pull/1771 !!!
