### ISSUE TITLE
Public Lab main page not accessible

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2128]
### Please describe the problem (or idea)

While accessing main page of publiclab getting an error
![screen shot 2018-01-26 at 2 36 47 pm](https://user-images.githubusercontent.com/20709985/35432689-d68a3608-02a6-11e8-94a6-e16eb2a3e425.png)

**Comment by SidharthBansal** [comment]
I am getting this for many pages

**Comment by ryzokuken** [comment]
Me too, @icarito any availability issues?

<img width="1680" alt="screen shot 2018-01-26 at 4 40 09 pm" src="https://user-images.githubusercontent.com/13121330/35437258-9ed38442-02b7-11e8-83e2-2c45f5f4fb37.png">

**Comment by sagarpreet-chadha** [comment]
Its accessible only if you are not logged in (try incognito mode) !

**Comment by icarito** [comment]
Checking this...

**Comment by icarito** [comment]
When I login in production, I get in logs:
```
Started POST "/user_sessions" for 181.65.123.201 at 2018-01-26 13:03:22 +0000
Processing by UserSessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4jdYjSSTg9jsBVjTcPIicGfuLNpLeuQ6NuomRzEQKA8=", "user_session"=>{"username"=>"icarito", "password"=>"[FILTERED]", "remember_me"=>"0"}, "return_to"=>"/"}
  Rendered notes/_responses.html.erb (22.9ms)
  Rendered home/_social.html.erb (0.1ms)
Completed 500 Internal Server Error in 34ms (ActiveRecord: 2.1ms)
  Rendered tag/_replication.html.erb (4.1ms)

NoMethodError (undefined method `valid_password?' for #<User:0x007f22e629c5d8>):
  lib/authlogic_openid/authlogic_openid/session.rb:73:in `save'
  app/controllers/user_sessions_controller.rb:27:in `create'


  Rendered tag/_tags.html.erb (14.5ms)
  Rendered tag/_tags.html.erb (0.1ms)
  Rendered tag/_location.html.erb (0.0ms)
  Rendered tag/_tagging.html.erb (20.3ms)
  Rendered notes/_comment.html.erb (17.8ms)
  Rendered notes/_comment.html.erb (18.3ms)
  Rendered notes/_comments.html.erb (38.9ms)
  Rendered notes/show.html.erb within layouts/application (495.1ms)
Read fragment views/feature_anniversary-banner (0.2ms)
Read fragment views/feature_sitewide-alert (0.1ms)
  Rendered layouts/_alerts.html.erb (0.3ms)
  Rendered layouts/_header.html.erb (6.8ms)
Read fragment views/feature_footer-notice (0.1ms)
  Rendered layouts/_footer.html.erb (1.8ms)
Completed 200 OK in 584ms (Views: 351.3ms | ActiveRecord: 181.6ms)
  Rendered stats/index.html.erb within layouts/application (7.9ms)
Read fragment views/feature_anniversary-banner (0.2ms)
Read fragment views/feature_sitewide-alert (0.1ms)
  Rendered layouts/_alerts.html.erb (0.5ms)
  Rendered layouts/_header.html.erb (4.1ms)
Read fragment views/feature_footer-notice (0.1ms)
  Rendered layouts/_footer.html.erb (1.4ms)
Completed 200 OK in 438ms (Views: 11.4ms | ActiveRecord: 116.9ms)
```

**Comment by icarito** [comment]
Not sure what could be wrong here, @jywarren I did `apt-get upgrade` last night and didn't notice any issues.

**Comment by jywarren** [comment]
https://github.com/binarylogic/authlogic/issues/216 ?

**Comment by icarito** [comment]
Whoa that is an old one, 2010? 😕

**Comment by jywarren** [comment]
OK, i restarted nginx and we're back up

**Comment by jywarren** [comment]
I think this is most likely related to `apt-get upgrade` somehow since there are no other changes in the past week... very odd. Closing for now but let's do a little investigating to see -- and keep an eye out!
