### ISSUE TITLE
Errors on recent git pull

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2172]
### Please describe the problem (or idea)
On recent git pull origin master I got the following error
```
ERROR["test_should_choose_i18n_for_wiki/_wiki_+_wiki/index", Minitest::Result, 33.54726393800229]
 test_should_choose_i18n_for_wiki/_wiki_+_wiki/index#Minitest::Result (33.55s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `author' for nil:NilClass
            app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb__4531670495430282201_69614740'
            app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/dashboard/_activity.html.erb:65:in `each'
            app/views/dashboard/_activity.html.erb:65:in `each_with_index'
            app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/home/home.html.erb:124:in `block in _app_views_home_home_html_erb__2767361777220498956_71702160'
            app/views/home/home.html.erb:123:in `_app_views_home_home_html_erb__2767361777220498956_71702160'
            app/controllers/home_controller.rb:20:in `home'
            test/integration/I18n_test.rb:277:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:275:in `each'
            test/integration/I18n_test.rb:275:in `block in <class:I18nTest>'

ERROR["test_should_choose_i18n_for_wiki/edit", Minitest::Result, 33.618710732029285]
 test_should_choose_i18n_for_wiki/edit#Minitest::Result (33.62s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `author' for nil:NilClass
            app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb__4531670495430282201_69614740'
            app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/dashboard/_activity.html.erb:65:in `each'
            app/views/dashboard/_activity.html.erb:65:in `each_with_index'
            app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/home/home.html.erb:124:in `block in _app_views_home_home_html_erb__2767361777220498956_71702160'
            app/views/home/home.html.erb:123:in `_app_views_home_home_html_erb__2767361777220498956_71702160'
            app/controllers/home_controller.rb:20:in `home'
            test/integration/I18n_test.rb:294:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:292:in `each'
            test/integration/I18n_test.rb:292:in `block in <class:I18nTest>'

ERROR["test_should_choose_i18n_for_wiki/revisions", Minitest::Result, 33.67818469303893]
 test_should_choose_i18n_for_wiki/revisions#Minitest::Result (33.68s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `author' for nil:NilClass
            app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb__4531670495430282201_69614740'
            app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/dashboard/_activity.html.erb:65:in `each'
            app/views/dashboard/_activity.html.erb:65:in `each_with_index'
            app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/home/home.html.erb:124:in `block in _app_views_home_home_html_erb__2767361777220498956_71702160'
            app/views/home/home.html.erb:123:in `_app_views_home_home_html_erb__2767361777220498956_71702160'
            app/controllers/home_controller.rb:20:in `home'
            test/integration/I18n_test.rb:311:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:309:in `each'
            test/integration/I18n_test.rb:309:in `block in <class:I18nTest>'

ERROR["test_should_choose_i18n_for_wiki/show", Minitest::Result, 33.73432698700344]
 test_should_choose_i18n_for_wiki/show#Minitest::Result (33.73s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `author' for nil:NilClass
            app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb__4531670495430282201_69614740'
            app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/dashboard/_activity.html.erb:65:in `each'
            app/views/dashboard/_activity.html.erb:65:in `each_with_index'
            app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb___4535329204358521855_73655320'
            app/views/home/home.html.erb:124:in `block in _app_views_home_home_html_erb__2767361777220498956_71702160'
            app/views/home/home.html.erb:123:in `_app_views_home_home_html_erb__2767361777220498956_71702160'
            app/controllers/home_controller.rb:20:in `home'
            test/integration/I18n_test.rb:321:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:319:in `each'
            test/integration/I18n_test.rb:319:in `block in <class:I18nTest>'
...
```
and many similar errors. Any help is highly appreciated. @publiclab/reviewers

**Comment by SidharthBansal** [comment]
I have got 41 errors and all have somewhat these files

**Comment by ViditChitkara** [comment]
Does remote 'origin' points to this repository? There might be a case, that you pulled from your local master and it was not properly synced with publiclab/plots2 master

**Comment by namangupta01** [comment]
@SidharthBansal does your origin pointing to remote plots 2 https://github.com/publiclab/plots2/ ?

**Comment by SidharthBansal** [comment]
Yesterday also it happened but got resolved automatically. On chat @jywarren was pointing to the 
>This line and ones like it are supposed to prevent that error but perhaps it's not working? https://github.com/publiclab/plots2/blob/master/db/schema.rb.example#L54

**Comment by SidharthBansal** [comment]
@ViditChitkara Yeah origin points to this repo, I checked that my head is on the latest commit of this plots2 repo

**Comment by SidharthBansal** [comment]
Sometimes all test cases are passing with this 
```
Emptying /home/sidharth/Desktop/Plots/plots2/test/reports
/home/sidharth/.rvm/gems/ruby-2.3.4/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: already initialized constant TagNodeAssociationExtension
/home/sidharth/.rvm/gems/ruby-2.3.4/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: previous definition of TagNodeAssociationExtension was here
Started with run options --seed 15415

  630/630: [===============================================================================================] 100% Time: 00:01:10, Time: 00:01:10

Finished in 70.29582s
630 tests, 1882 assertions, 0 failures, 0 errors, 0 skips

```
while other times it shows 41 errors

**Comment by SidharthBansal** [comment]
@ryzokuken can you help me with this? I am sometimes getting these errors while the other times not. It is completely insane to me.

**Comment by SidharthBansal** [comment]
Also getting this sometimes when I am getting this issue
![image](https://user-images.githubusercontent.com/20972099/35769509-15e99faa-0932-11e8-8669-0df78ef62126.png)
It was working fine. As soon as I reloaded the page the error came.

**Comment by ryzokuken** [comment]
@SidharthBansal let me look into this. This happens on `publiclab/master`?

**Comment by ryzokuken** [comment]
Any test failures?

**Comment by SidharthBansal** [comment]
It is on every branch or on no branch. I can't do anything due to this issue. The PRS which I have done are done in the time when there was no error. But when there is an error I can't do anything.

**Comment by SidharthBansal** [comment]
Nope. Only errors

**Comment by ryzokuken** [comment]
What I'm getting.

<img width="1680" alt="screen shot 2018-02-03 at 11 42 51 pm" src="https://user-images.githubusercontent.com/13121330/35770165-4741f228-093c-11e8-8405-7a5b0741a80b.png">

**Comment by ryzokuken** [comment]
We even send `node` down explicitly: 
```erb
<%= render partial: "dashboard/node_comment",  locals: { node: node, index: i } %>
```

**Comment by SidharthBansal** [comment]
Yeah I also get sometimes these kinds of errors too

**Comment by ryzokuken** [comment]
This error just disappeared. The site is also behaving erratically. Strange.

**Comment by SidharthBansal** [comment]
I have encountered many erratic errors too. After one logs off he gets directed to the remote login not found sometimes

**Comment by jywarren** [comment]
Hi, all - have you tried dumping your databases and rebuilding using `rake db:seed`? Alternatively also re-cloning your repository from Github to another directory to see if that's more consistent?

**Comment by jywarren** [comment]
I'm just thinking that if it doesn't seem to depend on what branch, and if you have confirmed you are at the same exact commit hash, then perhaps the problem is with the data?

**Comment by SidharthBansal** [comment]
Earlier I had this error so I did clone and did a rake db seed command. But now they are appearing. With rake db seed they are not going away.
I have pulled multiple times and checked if the errors are solved but they are not.
I will try to make a new clone and see.

**Comment by SidharthBansal** [comment]
One thing to note is ujjwal is also getting the node errors at home page which I have got some times. This indicates There is something going on in the code and that needs to be addressed

**Comment by SidharthBansal** [comment]
I have cloned the repo. For time being it is working fine. So closing it

**Comment by jywarren** [comment]
ok! that's good to hear but we can come back here if it comes up again.
Thanks!

**Comment by SidharthBansal** [comment]
Again errors have come on the git pull.
I have seen that the errors go after some hours after the git pull many times

**Comment by jywarren** [comment]
Hmm. Perhaps db seed doesn't actually empty the database? Can you trash your database file and try then?

**Comment by jywarren** [comment]
I'm sorry you're having such issues! Maybe `puts` a count of some ActiveRecord query in the failing tests to see if it returns a consistent # of wiki nodes? Some way to ensure the database is clean? I mean, tests shouldn't be running on an inconsistent database anyways, right? it should all come from fixtures.

**Comment by SidharthBansal** [comment]
Working fine nowadays. Hoping this error will not occur again
