### ISSUE TITLE
Upload image in question form seems broken? 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2187]
http://publiclab.org/questions/new

Is this working for other folks? I see an "upload failed" message. We should test this locally if possible!

**Comment by SidharthBansal** [comment]
Yeah, I am getting the upload failed message too. I have clicked on this button
![image](https://user-images.githubusercontent.com/20972099/35672096-70ac79b0-0763-11e8-81bd-0908ecc04e4a.png)

**Comment by SidharthBansal** [comment]
This is working fine for the research notes but not working here

**Comment by jywarren** [comment]
do you see the error in logs when running locally? I think that'll be the
next thing to check. Thanks!

**Comment by jywarren** [comment]
Investigating this -- locally i see: 

```
App 28642 stderr: [ 2018-03-30 17:25:22.9236 31016/0x2023db8(Worker 1) utils.rb ]: *** Exception EOFError in Rack application object (bad content body) (process 31016, thread 0x2023db8(Worker 1)):
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/multipart/parser.rb:83:in `block in fast_forward_to_first_boundary'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/multipart/parser.rb:81:in `loop'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/multipart/parser.rb:81:in `fast_forward_to_first_boundary'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/multipart/parser.rb:17:in `parse'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/multipart.rb:25:in `parse_multipart'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/request.rb:379:in `parse_multipart'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/request.rb:205:in `POST'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/methodoverride.rb:26:in `method_override'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/methodoverride.rb:14:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.16/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/actionpack-4.1.16/lib/action_dispatch/middleware/static.rb:84:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/railties-4.1.16/lib/rails/engine.rb:514:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/railties-4.1.16/lib/rails/application.rb:144:in `call'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/railties-4.1.16/lib/rails/railtie.rb:194:in `public_send'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/railties-4.1.16/lib/rails/railtie.rb:194:in `method_missing'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 28642 stderr:       from /home/warren/.rvm/gems/ruby-2.3.3/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

The POSTed request didn't even complete in the log, and had `Content-Length:44` -- cut off! 

As opposed to in `/post` where it works:

```
Started POST "/images" for 127.0.0.1 at 2018-03-30 17:27:18 -0400
Processing by ImagesController#create as JSON
  Parameters: {"image"=>{"photo"=>#<ActionDispatch::Http::UploadedFile:0x4b47e98 @tempfile=#<Tempfile:/tmp/RackMultipart20180330-31016-1w5nx7p>, @original_filename="micro
scopes.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"image[photo]\"; filename=\"microscopes.png\"\r\nContent-Type: image/png\r\n">}}
```

**Comment by jywarren** [comment]
Got it, I think!!! #2568
