### ISSUE TITLE
Upload main image button to rich editor at /post doesn't start uploading

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2529]
On https://publiclab.org/post (requires login), dragging an image in works fine, but (in Chrome/ChromeOS, Firefox Android both) clicking the "upload" button for the main image and selecting an image creates this JS error:

```js
Uncaught RangeError: Maximum call stack size exceeded
```

Dragging the image in works fine, as does upload in the legacy editor. 

The error seems to be related to line 1076 of `jquery.fileupload.js`:

```js
                    that._replaceFileInput(data.fileInput);
```
There's some issue with the callback `add()` method of `jQuery.callbacks`:

```
jQuery.Callbacks = function( options ) {
```

```
jquery.fileupload.js:1076 Uncaught RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (https://publiclab.org/lib/jquery-file-upload/js/jquery.fileupload.js:1076:26)
    at fire (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:3120:30)
    at Object.add [as done] (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:3166:7)
    at Object.always (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:3267:15)
    at $.(anonymous function).(anonymous function)._onChange (https://publiclab.org/lib/jquery-file-upload/js/jquery.fileupload.js:1073:53)
    at $.(anonymous function).(anonymous function)._onChange (https://publiclab.org/lib/jquery-file-upload/js/vendor/jquery.ui.widget.js:105:25)
    at HTMLInputElement.handlerProxy (https://publiclab.org/lib/jquery-file-upload/js/vendor/jquery.ui.widget.js:406:7)
    at HTMLInputElement.dispatch (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:4642:9)
    at HTMLInputElement.elemData.handle (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:4310:28)
    at Object.trigger (https://publiclab.org/assets/application-523218f5f81fa214d6e1c4cadcff366e.js:4551:12)
```

**Comment by 500swapnil** [comment]
I would like to help solve this. How do I proceed?

**Comment by jywarren** [comment]
This now works! Closing, thanks for your offer @500swapnil !
