### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#2754]
We have this on Travis:

```
The command "tail -n +2 -q ./test/reports/TEST*.xml >> output.xml" exited with 0.
0.73s$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/publiclab/plots2/pulls/2726: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.9.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/lib/danger/request_sources/github/github.rb:117:in `fetch_details'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:267:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/lib/danger/danger_core/executor.rb:28:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/lib/danger/commands/runner.rb:68:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.6.2/bin/danger:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi" exited with 1.
```

Can you please check this @jywarren, it's complaining of some bad credentials.

**Comment by jywarren** [comment]
Did you figure this out? :-)

**Comment by Gauravano** [comment]
hi guys, @jywarren have you verified that we are using correct tokens https://travis-ci.org/publiclab/plots2/builds/386823762#L443-L444. Also, I asked one of the contributors of Travis-ci ,https://github.com/travis-ci/travis-ci/issues/7574#issuecomment-393986930 , he pointed to `danger` commands. From dangerfile, we are just verifying our tokens on these lines(i guess). Thoughts?

**Comment by jywarren** [comment]
I think one thing to ask is why it /stopped/ working as of a few days ago.
What's changed? A GitHub policy? A token expired? Danger bot version bump?
