### ISSUE TITLE
rake db:migrate fails 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2882]
On recent git pull, when I tried to run tests, I was asked to run the pending migrations.
Upon running the pending migrations I got the following error
>Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class AddCommentViaColumnToComment < ActiveRecord::Migration[4.2]
....

I suppose this error is due to rails upgradation as indicated https://github.com/RolifyCommunity/rolify/issues/444 @Souravirus .
Can you please change the Migrations accordingly
Thanks

**Comment by Souravirus** [comment]
ok checking this bug. Thank you for reporting @SidharthBansal

**Comment by Souravirus** [comment]
can you paste the whole @SidharthBansal

**Comment by SidharthBansal** [comment]
```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddCommentViaColumnToComment < ActiveRecord::Migration[4.2]
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:525:in `inherited'
/home/sidharth/Desktop/plots2/db/migrate/20180605000000_add_comment_via_column_to_comment.rb:1:in `<top (required)>'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:962:in `load_migration'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:958:in `migration'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1305:in `use_transaction?'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1297:in `ddl_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1200:in `each'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1150:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1007:in `up'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:985:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddCommentViaColumnToComment < ActiveRecord::Migration[4.2]
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:525:in `inherited'
/home/sidharth/Desktop/plots2/db/migrate/20180605000000_add_comment_via_column_to_comment.rb:1:in `<top (required)>'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:962:in `load_migration'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:958:in `migration'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1305:in `use_transaction?'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1297:in `ddl_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1200:in `each'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1150:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:1007:in `up'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:985:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/home/sidharth/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by Souravirus** [comment]
ok thanks
