### ISSUE TITLE
Emoji in reply-by-email

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2928]
First, want to say that reply-by-email is AWESOME!!!!!!!

One small thing -- I tried sending a 🎉 in reply by email and got this error:

```

--000000000000cc5f67056f9393a7--

E, [2018-06-26T23:12:07.218298 #1] ERROR -- : Mysql2::Error: Incorrect string value: '\xF0\x9F\x8E\x89\x0A\x0A...' for column 'comment' at row 1: INSERT INTO `comments` (
`nid`, `uid`, `comment`, `timestamp`, `format`, `thread`, `comment_via`, `me
ssage_id`) VALUES (16574, 1, 'Testing response!\n  \n\nwith **formatting** &nbsp;<U+1F389>\n\n  \n\nOn Tue, Jun 26, 2018 at 5:01 PM \\<[do-not-reply@publiclab.org](mailto:do-not-reply@publiclab.org)\\> wrote:  \n\n> Public Lab contributor [warren](https://publiclab.org/profile/warren) just posted a new research note entitled \' **Are there lists of plants and the chemicals they can remediate?**\':\n> \n> Read and respond to the post here: [https://publiclab.org/notes/warren/06-26-2018/are-there-lists-of-plants-and-the-chemicals-they-can-remediate](https://publiclab.org/notes/warren/06-26-2018/are-there-lists-of-plants-and-the-chemicals-they-can-remediate)\n> \n> * * *\n> \n> I\'ve heard of compiled lists of plant species and the different things they can absorb from the air or soil or water. Does anyone know of such a list?\n> \n> * * *\n> \n> You received this email because you are subscribed to some or all of the following tags: .\n> \n> To change your preferences, please visit [https://publiclab.org/subscriptions](https://publiclab.org/subscriptions).\n> \n> Report spam and abuse to: [moderators@publiclab.org](mailto:moderators@publiclab.org)\n> \n> \r \r Check out the blog at [https://publiclab.org/blog](https://publiclab.org/blog) | Love our work? Become a Public Lab Sustaining Member today at [https://publiclab.org/donate](https://publiclab.org/donate)\n\n', 1530054727, 1, '01/', 1, 'CAGqfm_DFaA5h66ObwMsxFkgi5WwZHyByCniKbqpq1XfUAZj28A@mail.gmail.com')
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
```

**Comment by jywarren** [comment]
Want to try reproducing this issue in a test, then seeing if an encoding
change resolves it?

**Comment by namangupta01** [comment]
should i make a test for it?

**Comment by jywarren** [comment]
yeah, that sounds right. See if you can save a string with emoji in it
(there are some in the tests already, i think?) and then try creating a
node with it and see if it fails.

**Comment by namangupta01** [comment]
okay 👍

**Comment by jywarren** [comment]
I just tested this again since we finished upgrading the database for emoji unicode, by sending a reply to : https://publiclab.org/notes/warren/10-04-2018/reply-by-email-a-new-way-to-use-publiclab-org

`Testing emojis in reply by email! 🎉🙌❤`

It should process in a few minutes, let's see!
