### ISSUE TITLE
Various errors from production logs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2945]
Sorry to create a bunch of issues, but as I was searching for the problems with note pages, i happened to see a few 500 errors. Maybe a good start would be trying to reproduce these in a test?

There's an error coming up on production for the tag_controller:

`ArgumentError (no time information in "author"): app/controllers/tag_controller.rb:79:in `show'`

Full trace:

```
[b4a44df4-7296-4581-856a-b74846a0294f] Started GET "/maps/tag/bandwidth/author/dhaffnersr" for xxxxxxxx at 2018-06-28 17:42:19 +0000
[b4a44df4-7296-4581-856a-b74846a0294f] Processing by TagController#show as */*
[b4a44df4-7296-4581-856a-b74846a0294f]   Parameters: {"node_type"=>"maps", "id"=>"bandwidth", "start"=>"author", "end"=>"dhaffnersr"}
[b4a44df4-7296-4581-856a-b74846a0294f] Completed 500 Internal Server Error in 34ms (ActiveRecord: 30.9ms)
[b4a44df4-7296-4581-856a-b74846a0294f]   
[b4a44df4-7296-4581-856a-b74846a0294f] ArgumentError (no time information in "author"):
[b4a44df4-7296-4581-856a-b74846a0294f]   
[b4a44df4-7296-4581-856a-b74846a0294f] app/controllers/tag_controller.rb:79:in `show'
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered tag/_tags.html.erb (816.9ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered tag/_tags.html.erb (294.0ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered tag/_advanced_tagging.html.erb (38.5ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered tag/_location.html.erb (0.1ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered tag/_tagging.html.erb (1155.2ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered comments/_edit.html.erb (2.5ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered notes/_comment.html.erb (48.1ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered notes/_comment.html.erb (39.3ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered notes/_comments.html.erb (90.6ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   Rendered notes/show.html.erb within layouts/application (1867.1ms)
```

I also see an emoji-related issue -- @ViditChitkara would you mind taking a look?

```
[0fe497f8-9ffe-4c98-885b-96a78231e3f5] Completed 500 Internal Server Error in 2013ms (ActiveRecord: 528.4ms)
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   
[0fe497f8-9ffe-4c98-885b-96a78231e3f5] ActionView::Template::Error (undefined method `underscore' for nil:NilClass):  
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     119:   <div id="<%= str %>" class="navbar-text navbar-right pull-right" style="margin: 0;width: 100%;display: flex;border: 1px solid #e7e7e7;border-top: 0;">
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     120:     <% emoji_names, emoji_image_map = emoji_info %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     121:     <% emoji_like_map = comment.emoji_likes %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     122:     <% user_reactions_map = comment.user_reactions_map %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     123:     <% emoji_names.each do |e| %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     124:       <% capitalized_emoji_name = e.split("-").map(&:capitalize).join %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]     125:       <% str = "#{comment.id}-emoji-button-#{e}" %>
[0fe497f8-9ffe-4c98-885b-96a78231e3f5]   
[0fe497f8-9ffe-4c98-885b-96a78231e3f5] app/models/comment.rb:216:in `block in user_reactions_map'
[0fe497f8-9ffe-4c98-885b-96a78231e3f5] app/models/comment.rb:210:in `each'
```

**Comment by ViditChitkara** [comment]
Sure, I'll have a look!

**Comment by Souravirus** [comment]
Hi @jywarren, for the first error I have found a fix. Actually the thing was some other routes which has quite similar regex was being taken than the correct route. So, I repositioned the routes above that route.

**Comment by ViditChitkara** [comment]
Just fixed the second error!!

**Comment by ViditChitkara** [comment]
@jywarren should we write a migration to change all likes with emoji_type: nil with emoji_type: "ThumbsUp"? These likes were created before we published "like via reaction" features.

**Comment by jywarren** [comment]
sure - but isn't it `:+1:`? or is that not a standard emoji name?

**Comment by ViditChitkara** [comment]
Actually I found it easier to store "ThumbsUp" in emoji_type of like model. This would easily help me parse the corresponding emoji png. The name is however "+1" while using it in comment editor.
