### ISSUE TITLE
digest test function debugging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3005]
Hi, @ViditChitkara - just looking at the digest feature which i just tested - it no longer errors, but I'm not seeing the digest email arrive -- here is the mailman.log:

```
I, [2018-07-06T18:32:07.388085 #1]  INFO -- : Mailman v0.7.0 started
I, [2018-07-06T18:32:07.408103 #1]  INFO -- : Rails root found in ., requiring environment...
I, [2018-07-06T18:32:29.376341 #1]  INFO -- : POP3 receiver enabled (notifications@publiclab.org@pop.gmail.com).
I, [2018-07-06T18:32:29.405185 #1]  INFO -- : Polling enabled. Checking every 5 seconds.
I, [2018-07-06T18:34:17.738093 #1]  INFO -- : Got new message from 's_____@fuentelibre.org' with subject 'Re: New comment on GSOC-18 Email notification overhaul (#15750)'.
I, [2018-07-06T18:39:45.655506 #1]  INFO -- : Got new message from 'naman_____@gmail.com' with subject 'Re: New comment on GSoC proposal: Email integration Project (#15755)'.
I, [2018-07-06T19:23:53.775621 #1]  INFO -- : Got new message from 'notifications@publiclab.org' with subject 'New accessibility features for making aerial maps in MapKnitter (blog)'.
I, [2018-07-06T19:25:51.617264 #1]  INFO -- : Got new message from 'notifications@publiclab.org' with subject '[PublicLab] Building the coqui (#16652)'.
I, [2018-07-06T20:55:04.342859 #1]  INFO -- : Got new message from 'notifications@publiclab.org' with subject 'Company in Kuwait Cleaning  (event:rsvp)'.
I, [2018-07-06T20:55:04.424119 #1]  INFO -- : Got new message from 'notifications@publiclab.org' with subject 'Company in Kuwait Cleaning  (event)'.
I, [2018-07-06T23:53:43.358217 #1]  INFO -- : Mailman v0.7.0 started
I, [2018-07-06T23:53:43.494129 #1]  INFO -- : Rails root found in ., requiring environment...
I, [2018-07-06T23:54:05.393965 #1]  INFO -- : POP3 receiver enabled (notifications@publiclab.org@pop.gmail.com).
I, [2018-07-06T23:54:05.431230 #1]  INFO -- : Polling enabled. Checking every 5 seconds.
```

**Comment by jywarren** [comment]
Oddly i also see:

```
  Rendering subscription_mailer/send_digest.html.erb
  Rendered subscription_mailer/send_digest.html.erb (215.0ms)
Sent mail to jeff@publiclab.org (127.1ms)
```

**Comment by jywarren** [comment]
Is this a clue maybe? https://publiclab.org/sidekiq/retries

But why does it say mail sent to jeff@publiclab.org...?

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/42406997-8287f068-8181-11e8-8ed9-b87825f076d8.png)

**Comment by ViditChitkara** [comment]
Hmm, I see all failed attempts in sidekiq dashboard. The same socket error persists as it does in naman's pr yesterday. Will have to look into it. Yeah that's a bit odd. Would you mind checking your spam folder?
I'll look into the socket error, though.

**Comment by ViditChitkara** [comment]
I guess we also have sidekiq logs, maybe we could check that

**Comment by jywarren** [comment]
OK, i'll look at those!

**Comment by jywarren** [comment]
In sidekiq log, i see:

```
2018-07-09T21:24:42.139Z 1 TID-gopo9urzl WARN: {"context":"Job raised exception","job":{"class":"DigestMailJob","args":[],"retry":true,"queue":"default","jid":"78be3a26e8
6a591c13490743","created_at":1531109370.470904,"enqueued_at":1531171481.216972,"error_message":"getaddrinfo: Name or service not known","error_class":"SocketError","faile
d_at":1531109371.5504682,"retry_count":12,"retried_at":1531150608.9537182},"jobstr":"{\"class\":\"DigestMailJob\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"jid\"
:\"78be3a26e86a591c13490743\",\"created_at\":1531109370.470904,\"enqueued_at\":1531171481.216972,\"error_message\":\"getaddrinfo: Name or service not known\",\"error_clas
s\":\"SocketError\",\"failed_at\":1531109371.5504682,\"retry_count\":12,\"retried_at\":1531150608.9537182}"}
2018-07-09T21:24:42.139Z 1 TID-gopo9urzl WARN: SocketError: getaddrinfo: Name or service not known
2018-07-09T21:24:42.139Z 1 TID-gopo9urzl WARN: /usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:549:in `block in do_start'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:548:in `do_start'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `block in deliver'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:560:in `block in deliver_mail'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:558:in `deliver_mail'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `deliver'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/app/app/models/user.rb:391:in `send_digest_email'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/app/app/jobs/digest_mail_job.rb:6:in `perform'
/usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
```

**Comment by ViditChitkara** [comment]
@jywarren  I saw this error in naman's pr as well few days back. Some of the related issues:-
https://community.bitnami.com/t/bitnami-gitlab-vm-delayedmailer-error-error-message-getaddrinfo-temporary-failure-in-name-resolution-error-class-socketerror/26207
https://stackoverflow.com/questions/10920444/setting-static-ip-on-ubuntu-server-12-04-makes-loss-of-external-connection
@icarito any ideas? Is this related to permissions, just like the mailman config you did recently?

**Comment by jywarren** [comment]
Update via @icarito - 

```

I see
it's the smtp link to the docker host
we're "manually" adding 172.9.0.1 to the /etc/hosts file as host smtp
we do this for mailman and web container but sidekiq needs it too
```

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3058

**Comment by jywarren** [comment]
OK, i think this is complete -- please re-open if i'm wrong!
