### ISSUE TITLE
Welcome email error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3043]
I got an error when making a new account at PublicLab.org - the welcome email resulted in:

```
Processing by UsersController#create as HTML
[61eb879c-ff7e-465c-9313-eeecd7c33aea]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"vNQ1RXXVEokiCIlnO7i2T+EITl78k5uWQLhH/HcJ9AVr00RkGyU9Nl2BGm1NON/tO+gkJ0LJBh3uRjXf
F2WpaQ==", "user"=>{"username"=>"warren3423432234", "email"=>"j.ywarren@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "bio"=>""}, "g-recapt
cha-response"=>"03AEMEkEm_4nq8bHa0Cvg_nLo0ngoRbNaoHefFDYNwEpwSmywt5D3M7cNf-awyP5yyXpuIGKPxH3Ec23VcF_JB7bifJlDH9i0HIltDfU5N6t0Rm55_a-jJvG8dpv950n9ziK6XpNUY7RyI3WpC5o2fmvmD
62rPPeologrPf532Y7uYrTaL0qfPfP9VIQDsPkeCB0_8o6uiXWwNzb0Wd3KCVjVZRLAs6tJzJEgzR3ybINai_lTjxKHIlj1W5AwgOKvpp7Z1SLIieEpXyssPGGZ4OmbmiVpS_zoO4jP05GIW3WjIqtc436brWljTr_rXQ1lmVV
zKjBccNPaXYDzZ3iKAIfcGiQNGUI_4pECwHgERXwftSieExAZi-XZReFWIzAIiQUjHi4POglZUPHY0mOdBJix38hbO8XFPxyMH1zItfKEr5l3bs21OPpr3qLq78HCsNpvyc-hfz6X-"}
[61eb879c-ff7e-465c-9313-eeecd7c33aea]   Rendering welcome_mailer/notify_newcomer.html.erb
[61eb879c-ff7e-465c-9313-eeecd7c33aea]   Rendered welcome_mailer/notify_newcomer.html.erb (0.9ms)
[61eb879c-ff7e-465c-9313-eeecd7c33aea] Completed 500 Internal Server Error in 132ms (ActiveRecord: 25.9ms)
[61eb879c-ff7e-465c-9313-eeecd7c33aea]   
[61eb879c-ff7e-465c-9313-eeecd7c33aea] ActionView::Template::Error (undefined method `latest' for "":String):
[61eb879c-ff7e-465c-9313-eeecd7c33aea]     1: 
[61eb879c-ff7e-465c-9313-eeecd7c33aea]     2: <%= raw auto_link(@body.latest.render_body_email(ActionMailer::Base.default_url_options[:host]), sanitize: false) %>
[61eb879c-ff7e-465c-9313-eeecd7c33aea]     3: 
[61eb879c-ff7e-465c-9313-eeecd7c33aea]     4: <%= @footer %>
[61eb879c-ff7e-465c-9313-eeecd7c33aea]   
[61eb879c-ff7e-465c-9313-eeecd7c33aea] app/views/welcome_mailer/notify_newcomer.html.erb:2:in `_app_views_welcome_mailer_notify_newcomer_html_erb__596931266888483582_7024
2285831540'
[61eb879c-ff7e-465c-9313-eeecd7c33aea] app/mailers/welcome_mailer.rb:19:in `notify_newcomer'
[61eb879c-ff7e-465c-9313-eeecd7c33aea] app/controllers/users_controller.rb:23:in `create'
```

This looks pretty simple - could you try to resolve it pretty quick, since I think people can't sign up right now? Thank you, Gaurav!

**Comment by Gauravano** [comment]
@jywarren you are required to create a feature by name **email-email-body** as email body depends on it.

**Comment by jywarren** [comment]
Ah, we should have a fallback - check that it exists, you know? But I'll do that too. So this should be less urgent, i'll test again once i've made the feature. Thanks!

**Comment by jywarren** [comment]
Linking back to https://github.com/publiclab/plots2/issues/2241

Can you confirm that the email is sent also when people sign up with OAuth?

**Comment by Gauravano** [comment]
Sorry @jywarren correct name is **welcome-email-body** https://github.com/publiclab/plots2/issues/2241#issuecomment-403819732

**Comment by jywarren** [comment]
Hmm, i still see an error, actually!

**Comment by jywarren** [comment]
OK error is different now, related to #3040.

```
[9fb1e699-6430-4b20-bbaa-1c0734bd417a] Processing by UsersController#create as HTML
[9fb1e699-6430-4b20-bbaa-1c0734bd417a]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"bUOJ+/YEQaMKG6gSsGZaybnSl0umysDttYiZpVp6wr1UZvDMe1txM/9LX/m+JTCETxQIsYeYrALWlyYk
lpf8hw==", "user"=>{"username"=>"jywarren243253522", "email"=>"jyw.arren@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "bio"=>""}, "g-recap
tcha-response"=>"03AEMEkElnFQ3QcN08D8kAwL06iYeJEHsAq71i3CO3khVGUsFCCSsXFyFBbqy8tmSIeEuSJq-aW3xYivDmXKAYcnOOHs6WCOKlnDTRlR65J9cnwY3DWCXNibpzYxi07DfQQ-HageT0LTEL7fyDh4eFlFy
tHe6GDnvd_wCPLC5RyUzvXwu13giu69qCZGMKuLtVJxszuLmQRsf25RDFDnwWw_ii7qao8o7gMBKKWJ7JfyA9I0cNZaXgHyxgR4GJ5jlbdxvnfkh7aHebaai76wxPuX5irbePtkx57Ms2svBH9vZ8MrzhqYTCqbyBRyscG0dan
aVEhzQcsLpgYJi-BtNxtZPOZBvFmafcoCKGu6cFmOkryJi9kQOY2so"}
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239] Started GET "/login" for 46.229.168.71 at 2018-07-10 22:11:01 +0000
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239] Processing by UserSessionsController#new as HTML
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendering user_sessions/new.html.erb within layouts/application
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendered user_sessions/new.html.erb within layouts/application (7.1ms)
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendered layouts/_google_analytics.html.erb (0.1ms)
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendered layouts/_alerts.html.erb (0.3ms) [cache hit]
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendered layouts/_header.html.erb (3.0ms) [cache hit]
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239]   Rendered layouts/_footer.html.erb (0.3ms) [cache hit]
[c5835463-d4c6-4ecc-a8d5-cc2aa59ae239] Completed 200 OK in 14ms (Views: 10.2ms | ActiveRecord: 2.2ms)
[9fb1e699-6430-4b20-bbaa-1c0734bd417a]   Rendering welcome_mailer/notify_newcomer.html.erb
[9fb1e699-6430-4b20-bbaa-1c0734bd417a]   Rendered welcome_mailer/notify_newcomer.html.erb (6.2ms)
[9fb1e699-6430-4b20-bbaa-1c0734bd417a] Sent mail to jyw.arren@gmail.com (6.5ms)
[9fb1e699-6430-4b20-bbaa-1c0734bd417a] Completed 500 Internal Server Error in 185ms (ActiveRecord: 32.7ms)
[9fb1e699-6430-4b20-bbaa-1c0734bd417a]   
[9fb1e699-6430-4b20-bbaa-1c0734bd417a] Net::SMTPFatalError (550 relay not permitted
):
[9fb1e699-6430-4b20-bbaa-1c0734bd417a]   
[9fb1e699-6430-4b20-bbaa-1c0734bd417a] app/controllers/users_controller.rb:23:in `create'
```

**Comment by jywarren** [comment]
I pinged icarito... we'll see!

**Comment by SidharthBansal** [comment]
Here is the code where user is generated in OAuth
https://github.com/publiclab/plots2/blob/d86632929fc2cc14ee3d2580fc01477791b81e9f/app/models/user.rb#L429-L443
https://github.com/publiclab/plots2/blob/d86632929fc2cc14ee3d2580fc01477791b81e9f/app/controllers/user_sessions_controller.rb#L42-L49
This might help you @Gauravano

**Comment by icarito** [comment]
Hi pls test - We deployed with a new IP address and I switched the smtp configuration!

**Comment by Gauravano** [comment]
yes, signup working now! Thanks, @icarito!

**Comment by SidharthBansal** [comment]
Is it now integrated with providers @Gauravano ?

**Comment by Gauravano** [comment]
No @SidharthBansal , email would be sent only when signed up via our normal system. I will link it with providers tomorrow.

**Comment by SidharthBansal** [comment]
Great, good night @gauravano

**Comment by Gauravano** [comment]
Good night @SidharthBansal !

**Comment by jywarren** [comment]
Thanks everyone and good night!!!

**Comment by jywarren** [comment]
Confirmed - welcome email arrived!

![screen shot 2018-07-11 at 11 08 12 am](https://user-images.githubusercontent.com/24359/42581455-c5945f28-84fa-11e8-93c8-904889b3b370.png)
