### ISSUE TITLE
Mailman container crashes sometimes

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#3208]
```
icarito@rs-plots2:/srv/plots_container/plots2$ docker-compose logs mailman
Attaching to containers_mailman_1
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
mailman_1  | /usr/local/lib/ruby/2.4.0/net/pop.rb:1006:in `check_response_auth': -ERR [SYS/TEMP] Temporary system problem.  Please try again later. n16-v6mb15266ybd (Net::POPAuthenticationError)
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:905:in `auth'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:567:in `do_start'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:537:in `start'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:31:in `connect'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:132:in `block in polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
mailman_1  |    from script/mailman_server:22:in `<main>'
icarito@rs-plots2:/srv/plots_container/plots2$ 
```

**Comment by icarito** [comment]
Thanks for your wonderful work @namangupta01 !

**Comment by icarito** [comment]
I think mailman is crashing when Gmail responds "try later" - this will happen from time to time as no service is 100% up.

Is there an option with mailman for it to not abort in this case, or else we can look at docker-compose options for restarting crashed services.

**Comment by icarito** [comment]
Here's others with the same issue:
https://stackoverflow.com/questions/40554948/mailman-server-crashes-on-pop3-authentication-failure-in-rails

And a related issue at mailman repo:
https://github.com/mailman/mailman/issues/74

I would prefer if we catched `Net::POPAuthenticationError` rather than use Docker to restart a crashing program.

**Comment by icarito** [comment]
Not sure how to implement it but here's a script that's supposed to rescue from this error:

https://github.com/mailman/mailman/issues/74#issuecomment-165330029
```
  Daemons.run_proc("mailman_server", :dir => pid_dir, :dir_mode => :normal) do
    begin
      Mailman.config.logger = Logger.new(Rails.root.join("log/mailman.log"))
      Mailman.config.pop3 = APP_CONFIG[:mailman_accounts_auth_settings]
      Mailman.config.poll_interval = 60
      Mailman.config.ignore_stdin = true

      Mailman::Application.run do
        to(/^..................$/) do |identifier|
          ActiveRecord::Base.verify_active_connections!
          # Other code here
        end
      end
    rescue Net::POPAuthenticationError
      retry # Error is temporary - simply keep retrying it
    rescue IOError
      retry # Connection already closed, so ignore and retry
    rescue => exception
      # The Mailman process has thrown an error and stopped.
      Rollbar.error(exception) # Report it
      retry                    # Restart it
    end
  end
```

**Comment by icarito** [comment]
So it appears mailman crashes whenever POP3 mail checking fails (this could happen for a number of reasons and happens every now and then). I've made a patch to automatically restart it: https://github.com/publiclab/plots2/pull/3376 . It'd be even better if mailman could catch the error and not have to crash and restart. But nevertheless it should work!
