### ISSUE TITLE
Mailman doesn't have link to smtp server in production

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#3245]
Possibly `make redeploy-container` didn't run correctly or for some reason this line didn't seem to run because it's not in `/etc/hosts`.
Mailman was running but didn't process mail.

**Comment by icarito** [comment]
*this line* didn't run:
        docker-compose exec -T mailman bash -c "echo 172.19.0.1 smtp >> /etc/hosts"

**Comment by icarito** [comment]
```
icarito@rs-plots2:/srv/plots_container/plots2$ docker-compose logs mailman 
Attaching to containers_mailman_1
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
mailman_1  | /usr/local/lib/ruby/2.4.0/net/pop.rb:545:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:545:in `open'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:545:in `block in do_start'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:544:in `do_start'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:537:in `start'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:31:in `connect'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:132:in `block in polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
mailman_1  |    from script/mailman_server:22:in `<main>'
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
```

**Comment by icarito** [comment]
I'll run it manually for now.
