### ISSUE TITLE
Can't post comment on an answer to a question from firefox

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#3667]
### Please describe the problem (or idea)
couldn't post a comment on an answer to a question from firefox. I just clicked the publish button like 20 times w/ no action
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
nshapiro
> This can help us diagnose the issue: 

### Browser, version, and operating system
Firefox quantum 62.0 (64-bit) on mac 10.13.6 (17G65)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by yasmindias** [comment]
can I work on this issue?

**Comment by gauravano** [comment]
Hi @yasmindias, you are welcome to help with this issue. Thanks!

Hi @shapironick, could you please add the link to the answer as I tried posting a comment on a test answer and it worked for me - https://publiclab.org/questions/gauravano/10-11-2018/test-question-don-t-mark-as-spam . Thanks!

**Comment by shapironick** [comment]
thanks y'all! looks like it did end up posting after I navigated away from
the page to post the bug. sorry for the false alarm!

it was this answer i tried to comment on.
https://publiclab.org/questions/scotttees/10-09-2018/diy-oil-refinery-air-quality-monitoring

**Comment by gauravano** [comment]
Actually, sometimes when Email server goes down at that time too comment didn't get posted, so this may be the case. @jywarren @icarito could you check logs. Thanks!

**Comment by icarito** [comment]
Hey sorry for the delay, checking now the mailman service, sidekiq, and redis are up and running.

The logs for mailman do show a traceback and checking Docker it says `mailman` was restarted 8 hours ago so I guess it is failing regularly.

Here's the full log from `docker compose logs mailman`:

```
$ RAILS_ENV=production docker-compose -f containers/docker-compose-production.yml logs mailman  
Attaching to containers_mailman_1 
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension 
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here 
mailman_1  | /usr/local/lib/ruby/2.4.0/net/pop.rb:553:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello (OpenSSL::SSL::SSLError) 
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:553:in `do_start' 
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:537:in `start' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:31:in `connect' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:132:in `block in polling_loop' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run' 
mailman_1  |    from script/mailman_server:22:in `<main>' 
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
mailman_1  | /usr/local/lib/ruby/2.4.0/net/pop.rb:553:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write finished (OpenSSL::SSL::SSLError)
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:553:in `do_start'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:537:in `start' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:31:in `connect'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:132:in `block in polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run' 
mailman_1  |    from script/mailman_server:22:in `<main>'
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
mailman_1  | /usr/local/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:997:in `recv_response'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:993:in `get_response'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:935:in `block in stat'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:1013:in `critical'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:935:in `stat'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:626:in `n_mails'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:645:in `mails'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
mailman_1  |    from script/mailman_server:22:in `<main>'
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
```

Here's the compared uptime:
```
$ docker ps 
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                      NAMES 
d0373ebb12c1        containers_mailman   "script/mailman_serv…"   8 days ago          Up 8 hours                                     containers_mailman_1 
ed8dbc1b2e92        containers_web       "/bin/bash -c 'sleep…"   8 days ago          Up 8 days           127.0.0.1:4001->4001/tcp   containers_web_1 
30e4cd76dd24        containers_sidekiq   "bundle exec sidekiq…"   8 days ago          Up 8 days                                      containers_sidekiq_1 
2f1c91ed3dc8        mariadb:10.2         "docker-entrypoint.s…"   8 days ago          Up 8 days           3306/tcp                   containers_db_1 
c1b3d878071b        redis:latest         "docker-entrypoint.s…"   8 days ago          Up 8 days           6379/tcp                   containers_redis_1 
```
Notice it says **8 hours** not 8 days for mailman.
Hope it helps debug the issue!

**Comment by ebarry** [comment]
ok great -- are we able to close this issue?
