### ISSUE TITLE
Mailman failing to process some emails with `undefined method 'body'`

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#3807]
Comments are not being posted and an exception is logged:

mailman.log:
```
E, [2018-10-26T18:42:58.242934 #1] ERROR -- : Exception occurred while receiving message:
Return-Path: <plots-airquality+bncBDTNRHF7R4ARBZNVZXPAKGQE4XDXDZA@googlegroups.com>^M
Received: by 2002:a67:4cd8:0:0:0:0:0 with SMTP id h85csp1180639vsg;=0D=0A     ^M
   Fri, 26 Oct 2018 11:20:21 -0700 (PDT)^M
Received: from mail-sor-f55.google.com (mail-sor-f55.google.com. [209.85.220.55])        by mx.google.com with SMTPS id c18sor13686281qvs.10.2018.10.26.11.20.21        for <notifications@publiclab.org>        (Google Transport Security); Fri, 26 Oct 2018 11:20:21 -0700^M
Received: by 2002:a0c:aee3:: with SMTP id n35-v6ls1015357qvd.11.gmail; Fri,^M
 26=0D=0A Oct 2018 11:20:20 -0700 (PDT)^M
Date: Fri, 26 Oct 2018 11:20:19 -0700^M
From: Jeffrey Warren <jywarren@gmail.com>^M
Sender: plots-airquality@googlegroups.com^M
To: plots-airquality <plots-airquality@googlegroups.com>^M
Message-ID: <5607ca03-467d-45e6-b8b8-3d3b24a062d5@googlegroups.com>^M
In-Reply-To: <5bd345e6819ee_d92b2882f188dc1763b4@ed8dbc1b2e92.mail>^M
References: <5bd345e6819ee_d92b2882f188dc1763b4@ed8dbc1b2e92.mail>^M
Subject: [plots-airquality] Re: How can we connect a PMS5003 dust sensor to an^M
 Arduino? (#17406)^M
Mime-Version: 1.0^M
Content-Type: multipart/mixed;^M
 boundary="----=_Part_968_1525233980.1540578020082"^M
Content-Transfer-Encoding: 7bit^M
Delivered-To: notifications@publiclab.org^M
X-Received: by 2002:ac8:6656:: with SMTP id^M
 j22-v6mr4064545qtp.371.1540578021346;        Fri, 26 Oct 2018 11:20:21 -0700^M 
 (PDT)^M
ARC-Seal: i=1; a=rsa-sha256; t=1540578021; cv=none;        d=google.com;^M
 s=arc-20160816;       ^M
 b=kIwT95rz8S1ps8cQ/T2hm7leb9k9sx/CuHNQPMNKUxrx6ZDWvAfqypx0wuryScrSm+        ^M
 IGMpTUuRV1GhgLE/JqijtfUmpDXRk27pp624oCaKYRtXHDW1TAyVu3DcE/CQoBTbQdzf        ^M
 IwIP6j1fXsa8PXnmKBi/KatWjCBY9IeLM+cetX6yF5aW+qZqC6W/94FTM4ImIHxhvl7l        ^M
 xt5oiV+0cHurxQ9Jn+iOmMP6lKhCEEpWTHDE87xBg32aAeaa/IHD7fqgqcgAgN02sg7y        ^M
 lLASfvZGaJ6M63VPnEiDPfk3DU7WgxgvKpZuj1T2dKLhJX8Iqj0ra1GCdZFdoQSC8Aq0        ^M
 l7Vg==^M
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com;^M
 s=arc-20160816;       ^M
 h=list-unsubscribe:list-subscribe:list-archive:list-help:list-post        ^M
 :list-id:mailing-list:precedence:mime-version:subject:references        ^M
 :in-reply-to:message-id:to:from:date:sender:dkim-signature        ^M
 :dkim-signature;        bh=X6Ewf3ROjvTgRL/aRq/KncjSzuMuOOzAbh7Qo6uNrfY=;      ^M
  b=dq+q1OOvx9TZn52xng+YXxclRW47nzw5xOiwuL9H2+09HZfNIE8yrycMvT8z85G9cV        ^M
 +GBQyXCKMeSb9p8LDor7YPmx25+6a77prpCHAvm3rswAV7S3HLYkiNxBSEoN43g6ak3n        ^M
 lHLWUA2ctrs81Z8MIwuA03xrAVMm69Vl+/Qx1EJBiO2oFJLPBONtsY4476bUIdHClngF        ^M
 CaCq0rYfD0ibABdoHqt5tsVmAW6kCj5fRHTZGM3/MRIlmSXXHscgmJ7nl6y/q8bc6tDH        ^M
 xNmPqQeBYkrUlMLSXAQpcUHWKvWB+W+24S3DDBEd7Xpg+q+irUAKqSeKGdNaVss8l4gc        ^M
 05Aw==^M
ARC-Authentication-Results: i=1; mx.google.com;       dkim=pass^M
 header.i=@googlegroups.com header.s=20161025 header.b="UwGT/ZTc";      ^M
 dkim=pass header.i=@gmail.com header.s=20161025 header.b=q2sOF4oP;      ^M
 spf=pass (google.com: domain of^M
 plots-airquality+bncbdtnrhf7r4arbznvzxpakgqe4xdxdza@googlegroups.com^M
 designates 209.85.220.55 as permitted sender)^M
 smtp.mailfrom=plots-airquality+bncBDTNRHF7R4ARBZNVZXPAKGQE4XDXDZA@googlegroups.com;^M
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com^M
Received-SPF: pass (google.com: domain of^M
 plots-airquality+bncbdtnrhf7r4arbznvzxpakgqe4xdxdza@googlegroups.com^M
 designates 209.85.220.55 as permitted sender) client-ip=209.85.220.55;^M
Authentication-Results: mx.google.com;       dkim=pass^M
 header.i=@googlegroups.com header.s=20161025 header.b="UwGT/ZTc";      ^M
 dkim=pass header.i=@gmail.com header.s=20161025 header.b=q2sOF4oP;      ^M
 spf=pass (google.com: domain of^M
 plots-airquality+bncbdtnrhf7r4arbznvzxpakgqe4xdxdza@googlegroups.com^M
 designates 209.85.220.55 as permitted sender)^M
 smtp.mailfrom=plots-airquality+bncBDTNRHF7R4ARBZNVZXPAKGQE4XDXDZA@googlegroups.com;^M
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com^M
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;       ^M
 d=googlegroups.com; s=20161025;       ^M
 h=sender:date:from:to:message-id:in-reply-to:references:subject        ^M
 :mime-version:x-original-sender:precedence:mailing-list:list-id        ^M
 :list-post:list-help:list-archive:list-subscribe:list-unsubscribe;       ^M
 bh=X6Ewf3ROjvTgRL/aRq/KncjSzuMuOOzAbh7Qo6uNrfY=;       ^M
 b=UwGT/ZTcQbfFOVAE/OjN3sTABdMyarS/Fkn8CBsw7Pb9YMmYnrnpKUycJUfhS1/aLW        ^M
 XERfnQ+JBdi7am3RBWtu2VrBEnWHWCbsgQmzgKUqmmQi24hfB+aMdmGXvw0kfH/6BhYY        ^M
 AoWHd6xFjdhCRKHIzUQIWWMxKC9viMPrB9+XrSK2H7hrBbpi7I+C5+vbZCIfppZnanKK        ^M
 Ioobxcs2WBDAGHzHTCdwjHJp8iD4f895MlLibhwnTngpGYqIuK2DZlT4zq2heJtG01nB        ^M
 2eBiEEMicLy08++OpAoeoZC3LMrS101VWLIhwQ62Tyfl2lA503afHCy100H9bZnYns0w        ^M
 ifqw==^M
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;        d=gmail.com;^M
 s=20161025;       ^M
 h=date:from:to:message-id:in-reply-to:references:subject:mime-version        ^M
 :x-original-sender:precedence:mailing-list:list-id:list-post        ^M
 :list-help:list-archive:list-subscribe:list-unsubscribe;       ^M
 bh=X6Ewf3ROjvTgRL/aRq/KncjSzuMuOOzAbh7Qo6uNrfY=;       ^M
 b=q2sOF4oPexNw7iJYMacXeZlxD0RRPHVLb7MpX6gO1/FBVnnoqNGVPIuMpoYnoxWPK5        ^M
 aAZa6FK/zyj6iv9l+HnpbWwiSqixH+KOpvpep+CjWGHQCJYzrRtUMRtjax/bjdQAoFuA        ^M
 Ehe8RtKFZhiOU8DVNAh1gw5lwep/5srlesY6/KYTf/JofqBdpW+4chEwJitVWJRM0fwh        ^M
 q9fB/+KqD3edZsujtczsC+8sbwT5FfZq9qdBaX6rQDHArCjcZMELcqujBsc2tsVUcdIm        ^M
 57i8kxKUyqKNntdpB7l/gvDgG2dHiF4DQDkxCJzV3tvFpZT4+rXXYHykZRUPWTHvOI/y        ^M
 MwSg==^M
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;       ^M
 d=1e100.net; s=20161025;       ^M
 h=sender:x-gm-message-state:date:from:to:message-id:in-reply-to        ^M
 :references:subject:mime-version:x-original-sender:precedence        ^M
 :mailing-list:list-id:x-spam-checked-in-group:list-post:list-help        ^M
 :list-archive:list-subscribe:list-unsubscribe;       ^M
 bh=X6Ewf3ROjvTgRL/aRq/KncjSzuMuOOzAbh7Qo6uNrfY=;       ^M
 b=b64YJC9Wgkp1hj6FXJYwZ7IcIdLJmlZQz5lv17j6kNkIzcCyORyJmMOBImvmF4x8LR        ^M
 mkE1fqmMD3KRWZfIwuLAp4EtC9xEqOHj7sIWYS79KWIHsy8hmtZstbJElitVNeBBFvbe        ^M
 GSpl2nvASzjxC0Sl2MqWTFTRfGWtBGio6ew1isrqmfM/QdRTHjpNPB9ELwHFUN5Cefxt        ^M
 7z/xnNQtVd+2rkMSVBuAfxiWWtDXUK3IB4no2yVIsXsiI/+ukq43S2Y5odQwG0hpP3Xc        ^M
 LbDElhh3xSG22D3iUZcIcbV6DjA3jg5WktA27h+M+bqO1bKjaj51gK+k8OM/0MBnOxc2        ^M
 TeuQ==^M
X-Gm-Message-State: AGRZ1gJONcT2D43bP6MgblpY1mRpPXU895H7kU9sgwfgeaU7dPUDzuXa^M
 GWuZqfwVnPP4NaASCGCRkL4=^M
X-Google-Smtp-Source: AJdET5d5Ge95Z6aktmKQj5z7AXhG05X4+wm9dBd3ToHSkKdUmgBevwMTnwhOCUO+2f2ABlpLsAzXCQ==^M
X-Received: by 2002:a0c:b49a:: with SMTP id c26mr59137qve.4.1540578021188;    ^M
    Fri, 26 Oct 2018 11:20:21 -0700 (PDT)^M
X-BeenThere: plots-airquality@googlegroups.com^M
X-Received: by 2002:a0c:9953:: with SMTP id i19mr58437qvd.7.1540578020630;    ^M
    Fri, 26 Oct 2018 11:20:20 -0700 (PDT)^M
X-Original-Sender: jywarren@gmail.com^M
Precedence: list^M
Mailing-list: list plots-airquality@googlegroups.com; contact^M
 plots-airquality+owners@googlegroups.com^M
List-ID: <plots-airquality.googlegroups.com>^M
X-Spam-Checked-In-Group: plots-airquality@googlegroups.com^M
X-Google-Group-Id: 148564794908^M
List-Post: <https://groups.google.com/group/plots-airquality/post>,^M
 <mailto:plots-airquality@googlegroups.com>^M
List-Help: <https://groups.google.com/support/>,^M
 <mailto:plots-airquality+help@googlegroups.com>^M
List-Archive: <https://groups.google.com/group/plots-airquality^M
List-Subscribe: <https://groups.google.com/group/plots-airquality/subscribe>,^M
 <mailto:plots-airquality+subscribe@googlegroups.com>^M
List-Unsubscribe: <mailto:googlegroups-manage+148564794908+unsubscribe@googlegroups.com>,^M
 <https://groups.google.com/group/plots-airquality/subscribe>^M
^M
^M
------=_Part_968_1525233980.1540578020082^M
Content-Type: multipart/alternative;^M
 boundary="----=_Part_969_372259913.1540578020082"^M
Content-Transfer-Encoding: 7bit^M
^M
^M
------=_Part_969_372259913.1540578020082^M
Content-Type: text/plain;^M
 charset=UTF-8^M
Content-Transfer-Encoding: 7bit^M
^M
Wow, this got a reply on my posted question real fast. Thank you!!!! ^M
^M
On Friday, October 26, 2018 at 12:45:33 PM UTC-4, notifications wrote:^M
>^M
> *How can we connect a PMS5003 dust sensor to an Arduino? ^M
> <https://publiclab.org/n/17406>* was tagged with *#air-quality ^M
> <https://publiclab.org/tag/air-quality>* by warren ^M
> <https://publiclab.org/profile/warren> ^M
>^M
> Read and respond to the post here: ^M
> https://publiclab.org/notes/warren/10-26-2018/how-can-we-connect-a-pms5003-dust-sensor-to-an-arduino^M
>^M
> You received this email because it was tagged with: air-quality.^M
>^M
> To change your preferences, please visit ^M
> https://publiclab.org/subscriptions.^M
>^M
> Report spam and abuse to: moderators@publiclab.org^M
> Check out the blog at https://publiclab.org/blog | Love our work? Become ^M
> a Public Lab Sustaining Member today at https://publiclab.org/donate ^M
>^M
^M
-- ^M
Post to this group at plots-airquality@googlegroups.com^M
^M
Public Lab mailing lists (http://publiclab.org/lists) are great for discussion, but to get attribution, open source your work, and make it easy for others to find and cite your contributions, please publish your work at http://publiclab.org^M
--- ^M
You received this message because you are subscribed to the Google Groups "plots-airquality" group.^M
To unsubscribe from this group and stop receiving emails from it, send an email to plots-airquality+unsubscribe@googlegroups.com.^M
For more options, visit https://groups.google.com/d/optout.^M
^M
------=_Part_969_372259913.1540578020082^M

(ommitted for brevity)

------=_Part_968_1525233980.1540578020082--^M

E, [2018-10-26T18:42:58.243171 #1] ERROR -- : getaddrinfo: Name or service not known
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:549:in `block in do_start'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:548:in `do_start'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `block in deliver'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:560:in `block in deliver_mail'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:558:in `deliver_mail'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `deliver'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/local/bundle/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/app/app/models/comment.rb:136:in `notify'
/app/app/models/comment.rb:287:in `add_comment'
/app/app/models/comment.rb:219:in `receive_mail'
script/mailman_server:27:in `block (2 levels) in <main>'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:43:in `block in get_messages'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
script/mailman_server:22:in `<main>'
```

**Comment by jywarren** [comment]
Hi, thanks! Where do you see the message `undefined method body` and can you paste in that part too?

This isn't related? `E, [2018-10-26T18:42:58.243171 #1] ERROR -- : getaddrinfo: Name or service not known`

**Comment by icarito** [comment]
Sorry for the confusion. The error mentioned is a different error in the same file.
The actual error with this email is the one you mention: 
```
E, [2018-10-26T18:42:58.243171 #1] ERROR -- : getaddrinfo: Name or service not known
```

**Comment by icarito** [comment]
The error causing the confusion was the following:
```
E, [2018-10-31T17:54:22.182739 #1] ERROR -- : Exception occurred while receiving message:
Return-Path: <kkoerner@cleanair.org>^M
Received: by 2002:a67:e885:0:0:0:0:0 with SMTP id x5csp3184258vsn;=0D=0A      ^M
  Wed, 31 Oct 2018 10:48:49 -0700 (PDT)^M
Received: from mail-sor-f41.google.com (mail-sor-f41.google.com. [209.85.220.41])        by mx.google.com with SMTPS id f6-v6sor5749442wmd.7.2018.10.31.10.48.48        for <notifications@publiclab.org>        (Google Transport Security); Wed, 31 Oct 2018 10:48:48 -0700^M
Date: Wed, 31 Oct 2018 10:48:48 -0700^M
From: Karl Koerner <kkoerner@cleanair.org>^M
To: notifications@publiclab.org^M
Message-ID: <CAHbpiA87V2+3NukHHJUyrCBtDcemtgjAG3kiboDDodv5S9bE+g@mail.gmail.com>^M
Subject: Out of the office 10/31 - 11/9 Re: Air Sensor Project (#17388)^M
Mime-Version: 1.0^M
Content-Type: text/html;^M
 charset=UTF-8^M
Content-Transfer-Encoding: base64^M
Content-Disposition: inline^M
Delivered-To: notifications@publiclab.org^M

<snip>

E, [2018-10-31T17:54:22.211908 #1] ERROR -- : undefined method `body' for nil:NilClass
/app/app/models/comment.rb:264:in `add_comment'
/app/app/models/comment.rb:219:in `receive_mail'
script/mailman_server:27:in `block (2 levels) in <main>'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:43:in `block in get_messages'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
script/mailman_server:22:in `<main>'
```

**Comment by angelllll** [comment]
209.85.220.41
https://mail.google.com/mail/u/0/h/13no1hp247vm3/?&th=167f5eed5293480c&q=isaalijuly@gmail.com&v=c&s=q

**Comment by jywarren** [comment]
Can we check if either of these are still happening? Was the `getaddrinfo: Name or service not known` related to the mailman server not working or something? Or needing to retry connecting? 

For the body undefined, were we able to solve that or is it still happening? Thanks!

**Comment by icarito** [comment]
These are all errors logged since December (without full traceback).

```
E, [2018-12-14T00:01:40.677320 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2018-12-14T00:01:40.697380 #1] ERROR -- : undefined method `body' for nil:NilClass                                            E, [2018-12-14T15:14:11.706425 #1] ERROR -- : Connection reset by peer - SSL_connect                                              E, [2018-12-17T02:07:52.046116 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2018-12-17T02:07:52.076991 #1] ERROR -- : undefined method `body' for nil:NilClass                                            E, [2019-01-03T23:29:20.842856 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-03T23:29:20.843058 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-03T23:29:20.981343 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-03T23:29:20.981558 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-03T23:29:21.132202 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-03T23:29:21.132414 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-03T23:29:22.499920 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-03T23:29:22.500169 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-03T23:29:25.595164 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-03T23:29:25.595384 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-03T23:29:27.483921 #1] ERROR -- : Exception occurred while receiving message:
E, [2019-01-03T23:29:27.484163 #1] ERROR -- : getaddrinfo: Name or service not known                                              E, [2019-01-08T14:25:43.125848 #1] ERROR -- : Exception occurred while receiving message:                                         E, [2019-01-08T14:25:43.155618 #1] ERROR -- : undefined method `body' for nil:NilClass
```
Hope it helps! Let me know if you need details!
