### ISSUE TITLE
Installation Issue on Win 10

### ISSUE THREAD

**Issue by shriyakaneriya** [publiclab/plots2#3897]
I cannot run bundle install with the current version of openssl

Dell@DESKTOP-ABNBASD MINGW64 ~/plots2 (master)
$ bundle install
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.........
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 1.1.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using builder 3.2.3
Using erubi 1.7.1
Using mini_portile2 2.3.0
Using nokogiri 1.8.5 (x86-mingw32)
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.0
Using rack 2.0.5
Using rack-test 1.1.0
Using actionpack 5.2.0
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 5.2.0
Using globalid 0.4.1
Using activejob 5.2.0
Using mini_mime 1.0.1
Using mail 2.7.0
Using actionmailer 5.2.0
Using activemodel 5.2.0
Using arel 9.0.0
Using activerecord 5.2.0
Using multi_json 1.13.1
Using method_source 0.9.0
Using thor 0.19.4
Using railties 5.2.0
Using activerecord-session_store 1.1.1
Using mimemagic 0.3.2
Using marcel 0.3.2
Using activestorage 5.2.0
Using public_suffix 3.0.3
Using addressable 2.5.2
Using ansi 1.5.0
Using ast 2.4.0
Using request_store 1.4.1
Using ffi 1.9.25 (x86-mingw32)
Using ffi-compiler 1.0.1
Using scrypt 3.0.6
Using authlogic 4.4.2
Using hoe 3.17.0
Using authlogic-oid 1.0.4
Using descendants_tracker 0.0.4
Using ice_nine 0.11.2
Using axiom-types 0.1.1
Using bindex 0.5.0
Using bundler 1.17.1
Using chronic 0.10.2
Using ci_reporter 2.0.0
Using power_assert 1.1.3
Using test-unit 3.2.8
Using ci_reporter_test_unit 1.0.1
Using climate_control 0.2.0
Using coercible 1.0.0
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using coffee-rails 4.2.2
Using commonjs 0.2.7
Using composite_primary_keys 11.0.3
Using connection_pool 2.2.2
Using json 2.1.0
Using docile 1.3.1
Using simplecov-html 0.10.2
Using simplecov 0.16.1
Using tins 1.16.3
Using term-ansicolor 1.6.0
Using coveralls 0.8.22
Using diff-lcs 1.3
Using unf_ext 0.0.7.5 (x86-mingw32)
Using unf 0.1.4
Using domain_name 0.5.20180417
Using equalizer 0.0.11
Using multipart-post 2.0.0
Using faraday 0.12.2
Using figaro 1.1.1
Using friendly_id 5.2.4
Using gemoji 3.0.0
Using geocoder 1.5.0
Using geokit 1.13.1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.0
Using geokit-rails 2.3.1
Using georuby 2.0.0
Using mustermann 1.0.3
Using mustermann-grape 1.0.0
Using rack-accept 0.4.5
Using virtus 1.0.5
Using grape 1.1.0
Using grape-entity 0.7.1
Using grape-swagger 0.31.1
Using grape-swagger-entity 0.2.5
Using grape-swagger-rails 0.3.0
Using grape-swagger-ui 2.2.8
Using grease 0.3.1
Using hashie 3.5.7
Using highline 2.0.0
Using http-cookie 1.0.3
Using http_accept_language 2.1.1
Using i18n-js 3.0.11
Using impressionist 1.6.1
Using jasmine-core 2.99.2
Using jasmine-jquery-rails 2.0.3
Using phantomjs 2.1.1.0
Using jasmine-rails 0.14.8
Using jbuilder 2.7.0
Using jquery-atwho-rails 1.5.4
Using jquery-rails 4.3.3
Using json_expressions 0.9.0
Using jwt 1.5.6
Using launchy 2.4.3
Using less 2.6.0
Using tilt 2.0.8
Using less-rails 3.0.0
Using letter_opener 1.6.0
Using libv8 3.16.14.19
Using rb-fsevent 0.10.3
Using rb-inotify 0.9.10
Using ruby_dep 1.5.0
Using listen 3.1.5
Using maildir 2.2.1
Using mailman 0.7.0
Using metaclass 0.0.4
Using mime-types-data 3.2018.0812
Using mime-types 3.2.2
Using ruby-progressbar 1.10.0
Using minitest-reporters 1.3.5
Using mocha 1.7.0
Using multi_xml 0.6.0
Using netrc 0.11.0
Using nifty-generators 0.4.6
Using nokogumbo 2.0.0
Using oauth 0.5.4
Using oauth2 1.4.0
Using omniauth 1.8.1
Using omniauth-oauth2 1.5.0
Using omniauth-facebook 4.0.0
Using omniauth-github 1.3.0
Using omniauth-google-oauth2 0.5.3
Using omniauth-oauth 1.1.0
Using omniauth-twitter 1.4.0
Fetching openssl 2.1.2
Installing openssl 2.1.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/openssl-2.1.2/ext/openssl
C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20181105-13140-1tzzb3l.rb
extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for main() in -lws2_32... yes
checking for main() in -lgdi32... yes
checking for main() in -lcrypt32... yes
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.3.3/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-kerberos-dir
        --without-kerberos-dir
        --with-kerberos-include
        --without-kerberos-include=${kerberos-dir}/include
        --with-kerberos-lib
        --without-kerberos-lib=${kerberos-dir}/lib
        --with-debug
        --without-debug
        --enable-debug
        --disable-debug
        --with-nsllib
        --without-nsllib
        --with-socketlib
        --without-socketlib
        --with-ws2_32lib
        --without-ws2_32lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-gdi32lib
        --without-gdi32lib
        --with-crypt32lib
        --without-crypt32lib
extconf.rb:97:in `<main>': OpenSSL library could not be found. You might want to
use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is
installed. (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/openssl-2.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/openssl-2.1.2 for
inspection.
Results logged to
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/openssl-2.1.2/gem_make.out

An error occurred while installing openssl (2.1.2), and Bundler cannot continue.
Make sure that `gem install openssl -v '2.1.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  openssl

I have tried to point the installation to the openssl folder, but it returns as unknown switch
$ bundle install --with-openssl-dir=/mingw64/ssl
Unknown switches '--with-openssl-dir=C:/Program Files/Git/mingw64/ssl'

Also, I have checked to see if openssl is installed in the system.
$ openssl version -a
OpenSSL 1.0.2p  14 Aug 2018
built on: reproducible build, date unspecified
platform: mingw64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,2,long) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include -I/mingw64/include -D_WINDLL -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -g -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/mingw64/ssl"

A gem installation for openssl was recommended in the installation. But it does not work either. 
$ gem install openssl -v '2.1.2' --source 'https://rubygems.org/'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing openssl:
        ERROR: Failed to build gem native extension.

    current directory: C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/openssl-2.1.2/ext/openssl
C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20181105-10360-1sk8hfi.rb extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for main() in -lws2_32... yes
checking for main() in -lgdi32... yes
checking for main() in -lcrypt32... yes
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.3.3/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-kerberos-dir
        --without-kerberos-dir
        --with-kerberos-include
        --without-kerberos-include=${kerberos-dir}/include
        --with-kerberos-lib
        --without-kerberos-lib=${kerberos-dir}/lib
        --with-debug
        --without-debug
        --enable-debug
        --disable-debug
        --with-nsllib
        --without-nsllib
        --with-socketlib
        --without-socketlib
        --with-ws2_32lib
        --without-ws2_32lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-gdi32lib
        --without-gdi32lib
        --with-crypt32lib
        --without-crypt32lib
extconf.rb:97:in `<main>': OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed. (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/openssl-2.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/openssl-2.1.2 for inspection.
Results logged to C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/openssl-2.1.2/gem_make.out

**Comment by jywarren** [comment]
Hi, @shriyakaneriya -- have you been following this guide to installation on Windows? https://gorails.com/setup/windows/10

Otherwise, you may want to request a Cloud9 invite to run it there -- please send an email to web@publiclab.org to request this!

**Comment by quinn-codes-synthesis** [comment]
Hi @shriyakaneriya -- were you able to resolve this? Just wanted to offer assistance in case you hadn't. I also have Windows 10, and I remember definitely having some similar issues with the process of getting everything set up. :)

For future reference, I have found The Odin Project to be a great, free resource for tutorials like installing bundles. If you're still having trouble, I recommend trying your luck with one of the tutorials [here](https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites?ref=lnav). I ended up going with the virtual machine setup with Xubuntu, and so far that has been working well.

**Comment by CoderJolly** [comment]
@publiclab/reviewers

**Comment by gauravano** [comment]
@shriyakaneriya is your issue resolved?

**Comment by shriyakaneriya** [comment]
Hello everyone, 
I am sorry I haven't been able to keep up with this thread due to my exams, but yes, still facing the difficulty. @jywarren I did follow the given steps. Will try with the Cloud9 invite now. 
@quinn-codes-synthesis I have tried the WSL, but as suggested, it is not a good option. I will try using a Virtual Machine next. 
Thank you for the help, everyone.
Since OpenSSL is a problem, I have even tried attaching the destination where it is installed with the command, but that does not help. Would reinstalling OpenSSL in the given folder be advised?

**Comment by niravasher** [comment]
Hi! I get this error while installing mock server on windows 10.
Installing therubyracer 0.12.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/ext/v8
C:/Ruby25-x64/bin/ruby.exe -I C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0 -r
./siteconf20190122-15644-14ozghl.rb extconf.rb
checking for -lpthread... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
        --with-pthreadlib
        --without-pthreadlib
        --enable-debug
        --disable-debug
        --with-v8-dir
        --without-v8-dir
        --with-v8-include
        --without-v8-include=${v8-dir}/include
        --with-v8-lib
        --without-v8-lib=${v8-dir}/lib
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:50:in
`configure': By using --with-system-v8, you have chosen to use the version
(Libv8::Location::System::NotFoundError)
of V8 found on your system and *not* the one that is bundled with
the libv8 rubygem.

However, your system version of v8 could not be located.

Please make sure your system version of v8 that is compatible
with 3.16.14.19 installed. You may need to use the
--with-v8-dir option if it is installed in a non-standard location
from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/libv8-3.16.14.19/lib/libv8.rb:7:in
`configure_makefile'
        from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/therubyracer-0.12.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3 for inspection.
Results logged to
C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/therubyracer-0.12.3/gem_make.out

An error occurred while installing therubyracer (0.12.3), and Bundler cannot
continue.
Make sure that `gem install therubyracer -v '0.12.3' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  therubyracer


I tried to solve it using 'gem install therubyracer -v '0.12.3' but that also gives another error? Someone please help

**Comment by CoderJolly** [comment]
@niravasher In the error above, it states: 
"You have chosen to use the version(Libv8::Location::System::NotFoundError) of V8 found on your system and not the one that is bundled with the libv8 rubygem. "

I am still not sure bt please make sure your system version of v8 that is compatible with 3.16.14.19 installed.

**Comment by gauravano** [comment]
Hi @shriyakaneriya @niravasher, can we close this issue? Thanks!
