### ISSUE TITLE
Intermittent test failure with "undefined method `using_open_id?' for nil:NilClass"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3908]
We're seeing occasional non-repeatable test failures every once in a while (where another identical test run passes) showing the following errors:

```

ERROR["test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db", #<Minitest::Reporters::Suite:0x000055e9584d3e28 @name="UserTest">, 95.81481214999997]
 test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db#UserTest (95.81s)
NoMethodError:         NoMethodError: undefined method `using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in `authenticating_with_openid?'
            app/models/user.rb:454:in `block in create_with_omniauth'
            app/models/user.rb:447:in `create_with_omniauth'
            test/unit/user_test.rb:207:in `block in <class:UserTest>'
ERROR["test_user_creation", #<Minitest::Reporters::Suite:0x000055e9570a6540 @name="UserTest">, 96.59146871400003]
 test_user_creation#UserTest (96.59s)
NoMethodError:         NoMethodError: undefined method `using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in `authenticating_with_openid?'
            lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in `save'
            test/unit/user_test.rb:10:in `block in <class:UserTest>'
```

Not sure why! This is an example: https://travis-ci.org/publiclab/plots2/builds/451172024 although i've restarted it and perhaps it will pass now...

**Comment by jywarren** [comment]
Ah, this is a duplicate with #3059 that @Souravirus has been tracking over the past few months. Merging with that issue now.
