### ISSUE TITLE
rake db:migrate causes "primary key" error on some Macs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#429]
### What happened just before the problem occurred

@vzhz ran `rake db:migrate` on a mac, and got this:

````
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:458:in `method_missing'
/Users/Admin/Desktop/git/plots2/db/migrate/20120101000000_drupal_schema.rb:4:in `up'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:410:in `block in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:389:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:528:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:777:in `call'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:777:in `ddl_transaction'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:719:in `block in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:700:in `each'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:700:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:570:in `up'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:551:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/Users/Admin/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/Admin/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
````

This seems to be due to the `primary_key` directive on line four of our first migration (https://github.com/publiclab/plots2/blob/master/db/migrate/20120101000000_drupal_schema.rb#L4):

          create_table "comments", :primary_key => "cid", :options=>'ENGINE=MyISAM' do |t|

[This post shows](http://stackoverflow.com/questions/4769725/rails-migration-create-table-primary-key) that primary key columns must be described in the `create_table` block

````ruby
create_table(:global_feeds, :primary_key => 'guid') do |t|
  t.column :guid, "varchar(25)", :null => false
  ...
end
````

Our migration does *not* do this. For 17 instances in that file, we don't actually list the primary key -- for example, there is no line which says:

    t.integer "cid",                             :default => 0,  :null => false

This is weird because lots of people have installed the plots2 codebase, and our schema.rb file does not include them. 

Does this mean we should add them in? Should we change that migration, assuming that fixes the error that @vzhz saw? That would be weird, as it'd change the history of the states of the database, but if we don't, some proportion of people may have trouble installing the application at all. 

@vzhz - can you tell us what version of Mac OS you're using, and confirm that you installed mysql using `brew install mysql` - which I think I remember is correct? Thanks again!

****

If possible, we should do this as a new migration instead of changing an old one; checking about removing `rake db:migrate` from the README.md as a result: https://github.com/publiclab/plots2/commit/bc4bb1d6ac984c3266972805a2d64870fe83063d

**Comment by jywarren** [comment]
I'm closing this because our new process (#438) will never recommend `rake db:migrate` from a blank database, so this should not come up. We'll be shipping a pre-filled sqlite database to avoid this kind of issue with new contributors.
