### ISSUE TITLE
Resolve deprecation warning in preparation for Rails 6 (eventually)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4624]
Travis reports this warning several times:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "COUNT(term_data.tid) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in related at /app/app/models/tag.rb:328)
```

I believe we should wrap `term_data.tid` as recommended, like `Arel.sql(term_data.tid)` but am not 100% sure. This should make our test reports much more readable!

https://travis-ci.org/publiclab/plots2/builds/479677570#L3230

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by IshaGupta18** [comment]
Okay @jywarren so the deprecation warning has changed I think (atleast at my local machine) to this:

`DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "created ". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from tagNearbyNodes at /home/isha/plots2/app/services/search_service.rb:136)`

Also, the `line 328` has now been changes to this:

https://github.com/publiclab/plots2/blob/08d0f7d4e9b7c1e0d4d9d2e30c4b68c40162751e/app/models/tag.rb#L328

So I think we should probably address this new warning now, if I am correct. What do you think?

**Comment by IshaGupta18** [comment]
Okay so changing this line:
https://github.com/publiclab/plots2/blob/08d0f7d4e9b7c1e0d4d9d2e30c4b68c40162751e/app/services/search_service.rb#L136

to this:
`items.order("created #{Arel.sql(order_direction)}")`
gives these errors:
`ERROR["test_running_search_taglocations_with_valid_params", #<Minitest::Reporters::Suite:0x0000561e3d5ab9d0 @name="SearchServiceTest">, 71.05786943600106]
 test_running_search_taglocations_with_valid_params#SearchServiceTest (71.06s)
TypeError:         TypeError: no implicit conversion of nil into String
            app/services/search_service.rb:136:in `tagNearbyNodes'
            test/unit/api/search_service_test.rb:67:in `block in <class:SearchServiceTest>'

ERROR["test_running_search_taglocations_with_valid_params_and_specific_period", #<Minitest::Reporters::Suite:0x0000561e3d529980 @name="SearchServiceTest">, 71.07244423100201]
 test_running_search_taglocations_with_valid_params_and_specific_period#SearchServiceTest (71.07s)
TypeError:         TypeError: no implicit conversion of nil into String
            app/services/search_service.rb:136:in `tagNearbyNodes'
            test/unit/api/search_service_test.rb:75:in `block in <class:SearchServiceTest>'`
What do you think should be done?

**Comment by snpd25** [comment]
@IshaGupta18 What if we change the line `328` in `tag.rb` from:
  `.order(count: :desc)`
to:
`.order(Arel.sql('COUNT(term_data.tid) DESC'))`

**Comment by IshaGupta18** [comment]
I am so sorry @snpd25 I missed your comment, let me have a look at it ASAP.

**Comment by IshaGupta18** [comment]
I think that issue was probably resolved, could you have a look the Deprecation warning I have posted in https://github.com/publiclab/plots2/issues/4624#issuecomment-459947817 ? Thanks a lot!
