### ISSUE TITLE
THE SMALLEST BUG: error when adding tag `method`

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4774]
Hi everyone, 
I have a very, very, very small bug to report :) Alahna and I believe that it's only affecting the single tag `method`, as we've been able to add, then delete, then re-add any other tag we tried with no problems. We only experienced the bug on this this wiki page: https://publiclab.org/emery-board. 

Both alahna (regular user) and I (admin user) have attempted to add the tag `method` to that wiki page without success, however the details are different: 

* The regular user did not receive an error message when adding the tag `method`, and the tag box did not turn red, however upon reload the `method` tag was not there. 
* The Admin user (me) saw the tag box turn red as soon as i added the tag `method`, and an error message appeared to the far right side of my screen, check out this gif: 

![adding-tag-bug](https://user-images.githubusercontent.com/161439/52417122-220b6800-2ab9-11e9-85bc-1d8b3f816e52.gif)

## What we expected to see

We expected to be able to add the tag `method` to https://publiclab.org/emery-board. 
Thanks for reading!!!! Any ideas?

**Comment by gauravano** [comment]
I tried adding the `method` tag on the wiki/soil and it gave no error but when I tried on the wiki/emery-board, I got the same error. 

I will try to reproduce the error locally. Thanks for reporting @ebarry!

**Comment by gauravano** [comment]
@jywarren can you paste logs for the issue. I tried reproducing it, but haven't got anything. Althought, I will try with fresh eyes after getting sleep. Thanks!

**Comment by jywarren** [comment]
I think this is actually a mailing issue:

```
[787ceb4f-c5c4-4fcc-927e-49dad664a69d]   Rendering subscription_mailer/notify_tag_added.html.erb
[787ceb4f-c5c4-4fcc-927e-49dad664a69d]   Rendered subscription_mailer/notify_tag_added.html.erb (0.2ms)
[1e1d67a8-8642-4798-b984-d36035f14be1]   Rendered like/_like.html.erb (42.0ms)
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] Sent mail to notifications@publiclab.org (7.2ms)
[1e1d67a8-8642-4798-b984-d36035f14be1]   Rendered home/_social.html.erb (0.1ms)
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] Completed 500 Internal Server Error in 277ms (ActiveRecord: 209.0ms)
[787ceb4f-c5c4-4fcc-927e-49dad664a69d]   
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] Net::SMTPFatalError (550 relay not permitted
):
[787ceb4f-c5c4-4fcc-927e-49dad664a69d]   
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] app/models/node.rb:766:in `block in add_tag'
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] app/models/node.rb:736:in `add_tag'
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] app/controllers/tag_controller.rb:297:in `block in create'
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] app/controllers/tag_controller.rb:291:in `each'
[787ceb4f-c5c4-4fcc-927e-49dad664a69d] app/controllers/tag_controller.rb:291:in `create'
```

@icarito do you know why this might be? 

Not sure but there are 4 people following the `method` tag. 2 are gmail, one is hotmail, and one is me.

**Comment by icarito** [comment]
Indeed I missed an alert about this this evening. I'm checking what is wrong...

**Comment by icarito** [comment]
Hi,
I reviewed the logs for our MTA - mail transfer agent (Exim4) and found that Docker had changed the internal bridge IP address outside the 172.16.* range to 192.168.* internal IP address, and we were not relaying for that range. I've added that IP range and it's working again!
In order to avoid these issues we might consider adding a MTA

**Comment by ebarry** [comment]
Wow thanks everyone! Really appreciate it -- what an unexpected little bug!!!!!

**Comment by jywarren** [comment]
Great, thanks Sebastian! Shall we open a new issue for the MTA in
jywarren/web?
