### ISSUE TITLE
Public Lab website is down

### ISSUE THREAD

**Issue by Sairamdhandapani** [publiclab/plots2#6047]
Hi,

I typed publiclab.org on my browser and it said, We're sorry!! Try refreshing the page.
Attached image for reference.
![2019-07-23 09_22_51-MapKnitter](https://user-images.githubusercontent.com/17336308/61681587-ab42ee00-ad2b-11e9-9e4f-a34f18e0dfc2.png)

Thanks.

**Comment by Sairamdhandapani** [comment]
This is resolved.

**Comment by Sairamdhandapani** [comment]
Website is till down.

**Comment by jywarren** [comment]
Thanks for reporting, looking now...

**Comment by jywarren** [comment]
seeing `[8e073aa5-f7c3-4dc7-90aa-91928626ba53] Sending event a0fde0e32992428da65c51f9991f9af5 to Sentry
[8e073aa5-f7c3-4dc7-90aa-91928626ba53] Unable to record event with remote Sentry server (Raven::Error - the server responded with status 403 Error in headers is: Event dropped due to filter: web-crawlers):` too

**Comment by jywarren** [comment]
maybe we have to turn off websockets

**Comment by jywarren** [comment]
yes, the SMTP test is going wild! https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1563858120/6h/endpoints/AdminController%23smtp_test?responseType=error

**Comment by jywarren** [comment]
```
[8142b7fc-32f3-4e2d-a69c-a2903bfd0d23] Started GET "/smtp_test" for 50.57.61.6 at 2019-07-23 10:53:47 +0000
[8142b7fc-32f3-4e2d-a69c-a2903bfd0d23] Processing by AdminController#smtp_test as HTML
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] Completed 500 Internal Server Error in 129440ms (ActiveRecord: 0.0ms)
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] Sending event 730370d2f65e41d1a81f0f7a29d8eb03 to Sentry
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127]   
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] Errno::ETIMEDOUT (Connection timed out - connect(2) for "smtp" port 25):
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127]   
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] app/controllers/admin_controller.rb:369:in `initialize'
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] app/controllers/admin_controller.rb:369:in `new'
[b75d24d7-6a65-482f-b5c0-0a3e0ddc6127] app/controllers/admin_controller.rb:369:in `smtp_test'
```

**Comment by jywarren** [comment]
the error on the site is a 503 - service unavailable.

**Comment by jywarren** [comment]
https://sentry.io/share/issue/c6fb8a81f65a40b48f45b0f7f19f6bbe/

**Comment by jywarren** [comment]
Looking at setup in https://github.com/publiclab/plots2/issues/1606

**Comment by jywarren** [comment]
I ran `sudo service exim4 status` and got:

```
warren@rs-plots2:/srv/plots_container/plots2$ sudo service exim4 status
● exim4.service - LSB: exim Mail Transport Agent
   Loaded: loaded (/etc/init.d/exim4; generated; vendor preset: enabled)
   Active: active (exited) (Result: exit-code) since Sat 2019-06-22 11:21:41 UTC; 1 months 0 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 29173 ExecReload=/etc/init.d/exim4 reload (code=exited, status=0/SUCCESS)
      CPU: 56min 33.963s
  
Jul 18 07:52:15 rs-plots2 exim4[27925]: ALERT: exim paniclog /var/log/exim4/paniclog has non-zero size, mail system possibly broken
Jul 18 07:52:15 rs-plots2 systemd[1]: Reloaded LSB: exim Mail Transport Agent.
Jul 18 07:53:01 rs-plots2 systemd[1]: Reloading LSB: exim Mail Transport Agent.
Jul 18 07:53:01 rs-plots2 exim4[28327]: Reloading exim4 configuration files: exim4.
Jul 18 07:53:01 rs-plots2 exim4[28327]: ALERT: exim paniclog /var/log/exim4/paniclog has non-zero size, mail system possibly broken
Jul 18 07:53:01 rs-plots2 systemd[1]: Reloaded LSB: exim Mail Transport Agent.
Jul 18 08:00:20 rs-plots2 systemd[1]: Reloading LSB: exim Mail Transport Agent.
Jul 18 08:00:21 rs-plots2 exim4[29173]: Reloading exim4 configuration files: exim4.
Jul 18 08:00:21 rs-plots2 exim4[29173]: ALERT: exim paniclog /var/log/exim4/paniclog has non-zero size, mail system possibly broken
Jul 18 08:00:21 rs-plots2 systemd[1]: Reloaded LSB: exim Mail Transport Agent.
```

**Comment by jywarren** [comment]
```
2019-05-15 00:14:44 failed to write to main log: length=73 result=-1 errno=28 (No space left on device)
2019-05-15 00:10:13 spool directory space check failed: space=0 inodes=17667532
2019-05-15 00:15:13 failed to write to main log: length=73 result=-1 errno=28 (No space left on device)
2019-05-15 00:16:55 1hPyO2-0003uH-1R spool file write error while delivering: No space left on device
```

**Comment by jywarren** [comment]
I'm commenting out `smtp_test` until we figure it out and returning a simple string

**Comment by jywarren** [comment]
Solved by restarting `exim4` with `/etc/init.d/exim4 start` (or `systemctl start exim4`), thanks!
