### ISSUE TITLE
comment posting error due to email service downtime

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6273]
### Please describe the problem

I attempted to post a comment, but was shown this error: 

<img width="1280" alt="Screen Shot 2019-09-11 at 11 06 18 AM" src="https://user-images.githubusercontent.com/161439/64711833-403ea980-d488-11e9-99e8-4e6c572e978a.png">

I posted a second time, and got the same error. Then i left the tab open and went to do something else for a few minutes. Then i returned to the tab, and reloaded the page. My comment was there, it had posted twice actually, so i deleted the duplicate comment. 

I visited my email inbox, and noticed that i received two comment notification from the poster about their comment -- the comment that prompted me to visit and add another comment. See in the gif below that the first comment notification was blank, then a subsequent notification contained content: 

![comment-notification-reveals-error](https://user-images.githubusercontent.com/161439/64712215-d1ae1b80-d488-11e9-9d47-11cce4c6227c.gif)

> What did you expect to see that you didn't?

I expected my comment to post without error. 

### Please show us where to look

https://publiclab.org/notes/david_uwi/12-19-2018/particulate-sensor-using-a-stbm271

specifically: https://publiclab.org/notes/david_uwi/12-19-2018/particulate-sensor-using-a-stbm271#c25469

### What's your PublicLab.org username?

liz (admin)

### Browser, version, and operating system

Chrome on MacOS

**Comment by jywarren** [comment]
Hi, I saw the initial error myself. I think this is due to the mailing system being down, so the failure to send email notifications is resulting in an error, although that happens after the comment is actually recorded. 

Linking Sentry issue here re: email server outage. Should be an easy fix i think...

**Comment by jywarren** [comment]
`SocketError: getaddrinfo: Name or service not known` cc @icarito

**Comment by icarito** [comment]
Hi @ebarry @jywarren indeed the `mailman` container was down. I've restarted it and it has stopped again with no discernible reason beyond `containers_mailman_1 exited with code 1`.

The last error in logs is:     (but doesn't seem to be a fatal)
```
mailman_1  | /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query': Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x83\x0D ...' for column 'comment' at row 1: INSERT INTO `comments` (`nid`, `uid`, `comment`, `timestamp`, `format`, `thread`, `comment_via`, `message_id`) VALUES (19494, 503599, 'Hi, just a note. That document is not co
mplete. At many places things are not properly structured and grammatically incorrect. So, you all are welcomed to comment under it so that I can help you with further explanation. I have lot of ideas in my mind but didn\'t get much time to write them in the proposal.\nI agree with you Jeff on the last comment&nbsp;\n\nThanks all\n\n  \n<!-- @@$$%% Trimmed
Content @@$$%% -->On Sat, May 25, 2019 at 10:15 PM \\<[notifications@publiclab.org](mailto:notifications@publiclab.org)\\> wrote:  \n\n> Hi! There\'s been a response to a discussion you\'re involved in. You can reply to this email or visit this link:\r \r \r \r\n> \n> [https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comm
ents-welcome#c24254](https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c24254)\n> \n> **[warren](https://publiclab.org/profile/warren) wrote:**\n> \n> * * *\n> \n> Yes! Love this Newcomer --\\> Contributor --\\> Reviewer --\\> Maintainer --\\> Maintainer + Time to explore new repo and specialize in that 😃
\r \r \r \r This connects with and builds on what @sashadev-sky wrote in [https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019](https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019)\r \r \r \r Perhaps we could link from the first 3 steps to a longer \"journey
\" we encourage people to take, that has these extra steps!\r \r \r \r Re: diagram, yeah!!!! I was thinking of that when i made it, will add a link. It was a tough diagram to make, actually - and bigger and more complex than I\'d expected!\n> \n> * * *\n> \n> Look like spam?\r \r [Flag this](mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+L
ab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org//notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c24254+by+https://publiclab.org/profile/warren+Thanks! \"Flag as spam\") for moderators\n> \n> Reply at: [https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-so
ftware-roadmap-comments-welcome#comments](https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#comments)\n> \n> Report abuse to: [moderators@publiclab.org](mailto:moderators@publiclab.org)\n> \n> \r \r \r \r Check out the blog at [https://publiclab.org/blog](https://publiclab.org/blog) | Love ourwork? Become
a Public Lab Sustaining Member today at [https://publiclab.org/donate](https://publiclab.org/donate)\r \r \r \r \r \r \r \r If this email title has an ID in the format #0000, you can reply with the email you use at PublicLab.org and your responsewill be posted as a comment on the website.\n\n', 1568225014, 1, '0a/', 1, 'CAP9jS32vAk8GCXtY44Z2WLzQmwicGAM1F8gy
YBRitpsDBdn+tQ@mail.gmail.com') (ActiveRecord::StatementInvalid)                                                              
mailman_1  |    from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'                
mailman_1  |    from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'              
mailman_1  |    from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'                             
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'                                                
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'      
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'                               
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'                                
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'           
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free' 
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:33:in `exec_query'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:130:in `exec_insert'
mailman_1  |    from /usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/connection_adapters/abstract/database_statements.rb:6:in `insert'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:187:in `_insert_record'
mailman_1  |    from /usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/persistence.rb:64:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/counter_cache.rb:184:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/locking/optimistic.rb:70:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/attribute_methods/dirty.rb:140:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `block in _create_record'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/timestamp.rb:102:in `_create_record'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:705:in `create_or_update'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `block in create_or_update'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
mailman_1  |    from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `create_or_update'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:275:in `save'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/validations.rb:46:in `save'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:310:in `block in save'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:309:in `save'
mailman_1  |    from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:44:in `save'
mailman_1  |    from /app/app/models/node.rb:611:in `add_comment'
mailman_1  |    from /app/app/models/comment.rb:253:in `add_comment'
mailman_1  |    from /app/app/models/comment.rb:217:in `receive_mail'
mailman_1  |    from script/mailman_server:31:in `block (2 levels) in <main>'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:43:in `block in get_messages'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each'
mailman_1  |    from /usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop' 
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
mailman_1  |    from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
mailman_1  |    from script/mailman_server:22:in `<main>'
mailman_1  | #<Comment cid: 25474, pid: 0, nid: 20818, uid: 1, subject: "", comment: "Hi @mimiss, in case this is helpful! Hopingto add...", hostname: "", timestamp: 1568216558, status: 1, format: 1, thread: "01/", name: nil, mail: nil, homepage: nil, aid: 0, comment_via: 0, message_id: nil, tweet_id: nil, reply_to: nil>
```

**Comment by icarito** [comment]
Hi, I tried a few things including the full command list from Makefile and also removing / recreating the container, but it still crashes.
Here's a full log of a start->crash run.
http://paste.debian.net/1100148/

**Comment by icarito** [comment]
Here's another one from http://paste.debian.net/1100189/
which I got from running `docker-compose run mailman`.

I think this isolates the issue! 
** Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x83\x0D ...' for column 'comment' at row 1: INSERT INTO `comments` (`nid`, `uid`...**

```
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query': Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x83\x0D ...' for column 'comment' at row 1: INSERT INTO `comments` (`nid`, `uid`, `comment`, `timestamp`, `format`, `thread`, `comment_via`, `message_id`) VALUES (19494, 503599, 'Hi, just a note. That document is not complete. At many places things are not properly structured and grammatically incorrect. So, you all are welcomed to comment under it so that I can help you with further explanation. I have lot of ideas in my mind but didn\'t get much time to write them in the proposal.\nI agree with you Jeff on the last comment&nbsp;\n\nThanks all\n\n  \n<!-- @@$$%% Trimmed Content @@$$%% -->On Sat, May 25, 2019 at 10:15 PM \\<[notifications@publiclab.org](mailto:notifications@publiclab.org)\\> wrote:  \n\n> Hi! There\'s been a response to a discussion you\'re involved in. You can reply to this email or visit this link:\r \r \r \r\n> \n> [https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c24254](https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c24254)\n> \n> **[warren](https://publiclab.org/profile/warren) wrote:**\n> \n> * * *\n> \n> Yes! Love this Newcomer --\\> Contributor --\\> Reviewer --\\> Maintainer --\\> Maintainer + Time to explore new repo and specialize in that 😃\r \r \r \r This connects with and builds on what @sashadev-sky wrote in [https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019](https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019)\r \r \r \r Perhaps we could link from the first 3 steps to a longer \"journey\" we encourage people to take, that has these extra steps!\r \r \r \r Re: diagram, yeah!!!! I was thinking of that when i made it, will add a link. It was a tough diagram to make, actually - and bigger and more complex than I\'d expected!\n> \n> * * *\n> \n> Look like spam?\r \r [Flag this](mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org//notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c24254+by+https://publiclab.org/profile/warren+Thanks! \"Flag as spam\") for moderators\n> \n> Reply at: [https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#comments](https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#comments)\n> \n> Report abuse to: [moderators@publiclab.org](mailto:moderators@publiclab.org)\n> \n> \r \r \r \r Check out the blog at [https://publiclab.org/blog](https://publiclab.org/blog) | Love our work? Become a Public Lab Sustaining Member today at [https://publiclab.org/donate](https://publiclab.org/donate)\r \r \r \r \r \r \r \r If this email title has an ID in the format #0000, you can reply with the email you use at PublicLab.org and your response will be posted as a comment on the website.\n\n', 1568251771, 1, '0a/', 1, 'CAP9jS32vAk8GCXtY44Z2WLzQmwicGAM1F8gyYBRitpsDBdn+tQ@mail.gmail.com') (ActiveRecord::StatementInvalid)
	from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
	from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
	from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
	from /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:33:in `exec_query'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:130:in `exec_insert'
	from /usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/connection_adapters/abstract/database_statements.rb:6:in `insert'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:187:in `_insert_record'
	from /usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/persistence.rb:64:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/counter_cache.rb:184:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/locking/optimistic.rb:70:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/attribute_methods/dirty.rb:140:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `block in _create_record'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/timestamp.rb:102:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:705:in `create_or_update'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `block in create_or_update'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `create_or_update'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/persistence.rb:275:in `save'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/validations.rb:46:in `save'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
	from /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:310:in `block in save'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:309:in `save'
	from /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:44:in `save'
	from /app/app/models/node.rb:611:in `add_comment'
	from /app/app/models/comment.rb:253:in `add_comment'
	from /app/app/models/comment.rb:217:in `receive_mail'
	from script/mailman_server:31:in `block (2 levels) in <main>'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:43:in `block in get_messages'
	from /usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each'
	from /usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
	from /usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
	from script/mailman_server:22:in `<main>'
```

**Comment by icarito** [comment]
I *believe* this means there's a message in the queue with characters which our database currently can't decode.

**Comment by icarito** [comment]
This is related to https://github.com/publiclab/plots2/issues/5817 as it seems to be the same kind of stuck message in queue kind of thing.

**Comment by icarito** [comment]
I tried reverting to this version of mailman_server https://github.com/publiclab/plots2/commit/2bc7b498ef3a05bc090ef26f316a30ec0104bcc6#diff-331c6244d78f698043a2591c25d75d1e and starting the container. I also set it to run every 60 (not 20) seconds.

**Comment by icarito** [comment]
Okay so the hotfix in https://github.com/publiclab/plots2/pull/6275/files has allowed the container to keep on running. I guess the longer delay will help it handle the queue. Let's keep an eye on it!

**Comment by ebarry** [comment]
FYI i've now deleted these autoresponder messages from our site

**Comment by jywarren** [comment]
Linking with #3040, and closing now!
