### ISSUE TITLE
Users are unable to post Questions

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#7441]
The logs show an error with a non unique index: `index_node_vid`
```
[40293e6b-e44c-4a76-aa6b-deaadd433e81] Started POST "/notes/create?rich=true" for 181.67.173.136 at 2020-02-05 16:15:27 +0000
[40293e6b-e44c-4a76-aa6b-deaadd433e81] Processing by NotesController#create as */*
[40293e6b-e44c-4a76-aa6b-deaadd433e81]   Parameters: {"title"=>"Is the Ask Question feature working?", "body"=>"We've had reports of failure to post questions, this is a test!", "authenticity_token"=>"ndcajKRpcHwJg+Yfwg8nLc97OY3RQGVyBPYaROI9+yByvc0YqeOkMASw7ts5OeoqKFvige9f+M7E4KqBQwHhsg==", "draft"=>"false", "tags"=>"sysadmin", "has_main_image"=>"", "main_image"=>"", "node_images"=>"", "image"=>{"photo"=>""}, "rich"=>"true"}
[40293e6b-e44c-4a76-aa6b-deaadd433e81] Completed 500 Internal Server Error in 54ms (ActiveRecord: 37.0ms)
[40293e6b-e44c-4a76-aa6b-deaadd433e81] Sending event a7f6fc8f277148a3b2dad687e15df508 to Sentry
[40293e6b-e44c-4a76-aa6b-deaadd433e81]
[40293e6b-e44c-4a76-aa6b-deaadd433e81] ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '0' for key 'index_node_vid': INSERT INTO `node` (`type`, `title`, `uid`, `changed`, `comment`, `path`, `slug`) VALUES ('note', 'Is the Ask Question feature working?', 448589, 1580919327, 2, '/notes/icarito/02-05-2020/is-the-ask-question-feature-working', 'is-the-ask-question-feature-working')):
[40293e6b-e44c-4a76-aa6b-deaadd433e81]
[40293e6b-e44c-4a76-aa6b-deaadd433e81] app/models/node.rb:663:in `block in new_note'
[40293e6b-e44c-4a76-aa6b-deaadd433e81] app/models/node.rb:662:in `new_note'
[40293e6b-e44c-4a76-aa6b-deaadd433e81] app/controllers/notes_controller.rb:410:in `new_note'
[40293e6b-e44c-4a76-aa6b-deaadd433e81] app/controllers/notes_controller.rb:86:in `create'
```

**Comment by icarito** [comment]
This seems to be a reincidence of issue https://github.com/publiclab/plots2/issues/7062 - looking at how it was fixed then it seems there's a draft note with `index_node_vid`=0 causing this issue.

**Comment by icarito** [comment]
I deleted the invalid draft and this allowed posting again. I'll be working on the underlaying issue #3007
