### ISSUE TITLE
Ruby interpreter crashes on starting up with docker container

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#8707]
I'm trying to run Plots2 container without docker-compose.

I'm running it like this: `docker run --rm -ti -e PORT=18000 gcr.io/public-lab/plots2:nofs bash`
And it seems like the ruby interpreter crashes!
I tried upgrading base operating system from stretch to buster, same result.
Similar error is found when running under Google Cloud Run, but it's impossible to retrieve the backtrace. This is the goal, to run Plots2 under GCloud Run.

You can stop Phusion Passenger Standalone by pressing Ctrl-C.                                                                                                      
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/                                            
===============================================================================                                            
[ N 2020-10-30 19:34:42.9865 295/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f59c82b0872                                                                                                                       
App 340 output: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]                                                  
App 340 output:                                                                                               
App 340 output: -- Control frame information -----------------------------------------------                 
App 340 output: c:0043 p:---- s:0204 e:000203 CFUNC  :open                                                            
App 340 output: c:0042 p:0022 s:0198 e:000197 BLOCK  /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:112 [FINISH]
App 340 output: c:0041 p:---- s:0189 e:000188 CFUNC  :each                                                      
App 340 output: c:0040 p:0113 s:0185 e:000184 BLOCK  /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:109 [FINISH]
App 340 output: c:0039 p:---- s:0178 e:000177 CFUNC                                                                            
App 340 output:  :map                                                                                                                 
App 340 output: c:0038 p:0069 s:0174 e:000173 METHOD /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:99                          
App 340 output: c:0037 p:0079 s:0167 e:000166 CLASS  /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:11                        
App 340 output: c:0036 p:0007 s:0163 e:000162 CLASS  /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:6              
App 340 output: c:0035 p:0014 s:0160 e:000159 TOP    /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:5 [FINISH]
App 340 output: c:0034 p:---- s:0157 e:000156 CFUNC  :require_relative   
App 340 output: c:0033 p:0021 s:0152 e:000151 TOP    /usr/local/bundle/gems/sassc-2.2.1/lib/sassc.rb:31 [FINISH]           
App 340 output: c:0032 p:---- s:0149 e:000148 CFUNC  :require
App 340 output: c:0031 p:0006 s:0144 e:000143 METHOD /usr/local/bundle/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118
App 340 output: c:0030 p:0008 s:0138 e:000137 BLOCK  /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291
App 340 output: c:0029 p:0068 s:0135 e:000134 METHOD /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257    
App 340 output: c:0028 p:0011 s:0128 e:000127 METHOD /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291
App 340 output: c:0027 p:0013 s:0122 e:000121 TOP    /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5 [FINISH]                            
App 340 output: c:0026                             
App 340 output: p:---- s:0119 e:000118 CFUNC  :require_relative                                                              
App 340 output: c:0025 p:0006 s:0114 e:000113 TOP    /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3 [FINISH]
App 340 output: c:0024 p:---- s:0111 e:000110 CFUNC  :require                                                               
App 340 output: c:0023                                                    
App 340 output: p:0033 s:0106 e:000105 BLOCK  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:74 [FINISH]      
App 340 output: c:0022 p:---- s:0101 e:000100 CFUNC  :each                         
App 340 output:                                                                                                       
App 340 output: c:0021 p:0050 s:0097 e:000096 BLOCK  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:69
App 340 output:  [FINISH]                                                                                                                              
App 340 output: c:0020 p:---- s:0090 e:000089 CFUNC                                                          
App 340 output:  :each                                                                                                       
App 340 output: c:0019 p:0030 s:0086 e:000085 METHOD                                                             
App 340 output:  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:58                                                                                       
App 340 output: c:0018 p:0015 s:0081 e:000080                                                                             
App 340 output: METHOD /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:174                                                                              
App 340 output: c:0017 p:0062 s:0076 e:000075                                                                                         
App 340 output: TOP    /app/config/application.rb:8 [FINISH]                                                                          
App 340 output: c:0016 p:---- s:0073                                                                                                                   
App 340 output: e:000072 CFUNC  :require_relative                                                                           
App 340 output: c:0015 p:0006 s:0068                                                                                         
App 340 output: e:000067 TOP    /app/config/environment.rb:2 [FINISH]                                                        
App 340 output: c:0014 p:---- s:0065 e:000064 CFUNC  :require_relative                                                      
App 340 output:                                                                                                                                                  
App 340 output: c:0013 p:0007 s:0060 e:000059 BLOCK  config.ru:3                                                          
App 340 output:  [FINISH]                                                                                       
App 340 output: c:0012 p:---- s:0057 e:000056 CFUNC                                                       
App 340 output:  :instance_eval                                                                                              
App 340 output: c:0011 p:0040 s:0053 e:000052 METHOD                                                                  
App 340 output:  /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:125 [FINISH]                                                                              
App 340 output: c:0010 p:---- s:0047 e:000046                                                                                
App 340 output: CFUNC  :new                                                                                      
App 340 output: c:0009 p:0013 s:0043 e:000042                                                                                                                    
App 340 output: EVAL   config.ru:1 [FINISH]                                                                               
App 340 output: c:0008 p:---- s:0040                                                                                         
App 340 output: e:000039 CFUNC  :eval                                                                    
App 340 output: c:0007 p:0164                                                                                               
App 340 output: s:0033 e:000032 METHOD /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:101
App 340 output: c:0006 p:0005                                                                           
App 340 output: s:0025 e:000024 BLOCK  /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:189
App 340 output: c:0005                                
App 340 output: p:0015 s:0022 e:000021 METHOD /usr/local/bundle/gems/passenger-6.0.6/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:378
App 340 output: c:0004                                                                      
App 340 output: p:0156 s:0015 e:000014 CLASS  /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:188
App 340 output: c:0003                                                                                                       
App 340 output: p:0007 s:0009 e:000008 CLASS  /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:30
App 340 output: c:0002 p:0034 s:0006 e:000005 EVAL                                                                                                               
App 340 output:  /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:29 [FINISH]                  
App 340 output: c:0001                                                                                          
App 340 output: p:0000 s:0003 E:001520 (none) [FINISH]                                                   
App 340 output:                                                                                           
App 340 output: -- Ruby level backtrace information ----------------------------------------
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:29:in `<main>'
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:378:in `run_block_and_record_step_progress'
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:101:in `preload_app'       
App 340 output: /usr/local/bundle/gems/passenger-6.0.6/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 340 output: config.ru:1:in `<main>'                                                                               
App 340 output: config.ru:1:in `new'                                                    
App 340 output: /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'                                                              
App 340 output: /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'  
App 340 output: config.ru:3:in `block in <main>'                                                                             
App 340 output: config.ru:3:in `require_relative'                                             
App 340 output: /app/config/environment.rb:2:in `<top (required)>'                                                          
App 340 output: /app/config/environment.rb:2:in `require_relative'              
App 340 output: /app/config/application.rb:8:in `<top (required)>'                                      
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:174:in `require'   
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:58:in `require'                   
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:58:in `each'
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:69:in `block in require'
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:69:in `each'                       
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:74:in `block (2 levels) in require'                   
App 340 output: /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:74:in `require'                           
App 340 output: /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<top (required)>'                                                              
App 340 output: /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'                       
App 340 output: /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'             
App 340 output: /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
App 340 output: /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
App 340 output: /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
App 340 output: /usr/local/bundle/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'
App 340 output: /usr/local/bundle/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'
App 340 output: /usr/local/bundle/gems/sassc-2.2.1/lib/sassc.rb:31:in `<top (required)>'
App 340 output: /usr/local/bundle/gems/sassc-2.2.1/lib/sassc.rb:31:in `require_relative'
App 340 output: /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:5:in `<top (required)>'
App 340 output: /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:6:in `<module:SassC>'
App 340 output: /usr/local/bundle/gems/sassc-2.2.1/lib/sassc/native.rb:11:in `<module:Native>'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:99:in `ffi_lib'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:99:in `map'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:109:in `block in ffi_lib'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:109:in `each'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:112:in `block (2 levels) in ffi_lib'
App 340 output: /usr/local/bundle/gems/ffi-1.11.3/lib/ffi/library.rb:112:in `open'
App 340 output:
App 340 output: -- Machine register context ------------------------------------------------
App 340 output:  RIP: 0x00007f59c82b0872 RBP: 0x0000000000000002 RSP: 0x00007ffe390b24a0
App 340 output:  RAX: 0x00007ffe390b2500 RBX: 0x00007ffe390b24b0 RCX: 0x000000007373632e
App 340 output:  RDX: 0x0000000000000003 RDI: 0x00007f59c8438c20 RSI: 0x00007ffe390b24b0
App 340 output:   R8: 0x00007f59cc339d80  R9: 0x0000000000000000 R10: 0xfffffffffffffa4d
App 340 output:  R11: 0x00007f59cc21f020 R12: 0x00007f59c8a01100
App 340 output:  R13: 0x00005591108c7ce0
App 340 output:  R14: 0x00007f59c8420d38 R15: 0x0000000000000000 EFL: 0x0000000000010206
App 340 output:

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi Sebastian! I'm seeing the same issue in GitHub Actions about 80% of runs -- working the issue in https://github.com/publiclab/plots2/issues/8868 and it's linked to the `sassc-ruby` lib in https://github.com/sass/sassc-ruby/issues/146
