### ISSUE TITLE
Address test failures in GitPod

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8893]
We see a range of errors but nothing we haven't seen already. Maybe some would be solved by #8864?

``` FAIL["test_that_pinned_notes_with_\"pinned:foo\"_tags_appear_at_the_top_of_[nodes:foo]_inline_tables", #<Minitest::Reporters::Suite:0x0000563ce636f668 @name="NodeSharedTest">, 10.334103200992104]
 test_that_pinned_notes_with_"pinned:foo"_tags_appear_at_the_top_of_[nodes:foo]_inline_tables#NodeSharedTest (10.33s)
        Expected: 1
          Actual: 0
        test/unit/node_shared_test.rb:24:in `block in <class:NodeSharedTest>'
```

> 1029 tests, 3446 assertions, 7 failures, 12 errors, 0 skips

_Originally posted by @jywarren in https://github.com/publiclab/plots2/pull/8856#issuecomment-749659409_

**Comment by jywarren** [comment]
> Indeed, other tests failing include test/editor_test.rb which we are working on in #8858

**Comment by jywarren** [comment]
Let's copy in tests that are still failing... looks like:

* action cable tests (we solved this in GitHub Actions using Redis, and redis is running in GitPod, so maybe just miconfigured?)
* some "wrong number of arguments" familiar from github actions migration in https://github.com/publiclab/plots2/pull/8795
* some "undefined method [] for nil"
* some Username already taken validation errors

Full log here: https://gist.github.com/jywarren/c6dc4d92ada5da0af6bfe8e960116d92

<details>
    <summary>Full log</summary>
<code>
 FAIL["test_running_search_nodes", #<Minitest::Reporters::Suite:0x00005568d7350ee0 @name="SearchServiceTest">, 11.643923052994069]
 test_running_search_nodes#SearchServiceTest (11.64s)
        Expected: 1
          Actual: 2
        test/unit/api/search_service_test.rb:56:in `block in <class:SearchServiceTest>'

 FAIL["test_running_search_questions", #<Minitest::Reporters::Suite:0x00005568d703daa0 @name="SearchServiceTest">, 13.711695559992222]
 test_running_search_questions#SearchServiceTest (13.71s)
        Expected: 4
          Actual: 3
        test/unit/api/search_service_test.rb:71:in `block in <class:SearchServiceTest>'

ERROR["test_search_Tag_Nearby_People_functionality", #<Minitest::Reporters::Suite:0x00005568d84eb290 @name="SearchApiTest">, 43.266241220000666]
 test_search_Tag_Nearby_People_functionality#SearchApiTest (43.27s)
Minitest::UnexpectedError:         NoMethodError: undefined method `[]' for nil:NilClass
            test/functional/api/search_api_test.rb:249:in `block in <class:SearchApiTest>'

ERROR["test_search_Tag_Nearby_People_functionality_with_specific_period", #<Minitest::Reporters::Suite:0x00005568d8547d38 @name="SearchApiTest">, 43.272401712994906]
 test_search_Tag_Nearby_People_functionality_with_specific_period#SearchApiTest (43.27s)
Minitest::UnexpectedError:         NoMethodError: undefined method `[]' for nil:NilClass
            test/functional/api/search_api_test.rb:312:in `block in <class:SearchApiTest>'

ERROR["test_search_Tag_Nearby_People_functionality_with_tag=awesome", #<Minitest::Reporters::Suite:0x00005568d7e85dd8 @name="SearchApiTest">, 43.279155743992305]
 test_search_Tag_Nearby_People_functionality_with_tag=awesome#SearchApiTest (43.28s)
Minitest::UnexpectedError:         NoMethodError: undefined method `[]' for nil:NilClass
            test/functional/api/search_api_test.rb:334:in `block in <class:SearchApiTest>'

ERROR["test_search_Tag_Nearby_People_functionality_wth_sort_by=recent", #<Minitest::Reporters::Suite:0x00005568d86b7240 @name="SearchApiTest">, 43.289038357004756]
 test_search_Tag_Nearby_People_functionality_wth_sort_by=recent#SearchApiTest (43.29s)
Minitest::UnexpectedError:         NoMethodError: undefined method `[]' for nil:NilClass
            test/functional/api/search_api_test.rb:290:in `block in <class:SearchApiTest>'

ERROR["test_search_Tag_Nearby_People_using_tag=spectrometer_and_field=node_tag", #<Minitest::Reporters::Suite:0x00005568d0ca9d18 @name="SearchApiTest">, 43.37354161399708]
 test_search_Tag_Nearby_People_using_tag=spectrometer_and_field=node_tag#SearchApiTest (43.37s)
Minitest::UnexpectedError:         NoMethodError: undefined method `[]' for nil:NilClass
            test/functional/api/search_api_test.rb:378:in `block in <class:SearchApiTest>'

 FAIL["test_search_question_at_/search/questions/question", #<Minitest::Reporters::Suite:0x00005568d783ddb8 @name="SearchControllerTest">, 86.73391509799694]
 test_search_question_at_/search/questions/question#SearchControllerTest (86.73s)
        Expected: 8
          Actual: 9
        test/functional/search_controller_test.rb:51:in `block in <class:SearchControllerTest>'

ERROR["test_user_with_duplicate_username_creation_with_create_with_omniauth", #<Minitest::Reporters::Suite:0x00005568d6305f90 @name="UserTest">, 135.80975082999794]
 test_user_with_duplicate_username_creation_with_create_with_omniauth#UserTest (135.81s)
Minitest::UnexpectedError:         ActiveRecord::RecordInvalid: Validation failed: Username has already been taken
            app/models/user.rb:459:in `block in create_with_omniauth'
            app/models/user.rb:450:in `create_with_omniauth'
            test/unit/user_test.rb:59:in `block in <class:UserTest>'

 FAIL["test_broadcast_only_to_users_with_notification_all_tag", #<Minitest::Reporters::Suite:0x00005568d6cf0668 @name="CommentNotificationTest">, 135.95907926300424]
 test_broadcast_only_to_users_with_notification_all_tag#CommentNotificationTest (135.96s)
        No messages sent with {:notification=>{:title=>"New Comment on This is purple-air with hyphen", :path=>"/notes/admin/02-20-2019/purple-air-with-hyphen", :option=>{:body=>"Hey, @naman18996, @jeffrey and @jeff. This is Action Cable Integration Test", :icon=>"https://publiclab.org/logo.png"}}} to users:notification:13
        test/action_cable/integration/comment_notification_test.rb:203:in `test_broadcast_only_to_users_with_notification_all_tag'

 FAIL["test_broadcasts_when_user_is_loggedin", #<Minitest::Reporters::Suite:0x00005568d7035418 @name="CommentNotificationTest">, 136.07327342199278]
 test_broadcasts_when_user_is_loggedin#CommentNotificationTest (136.07s)
        No messages sent with {:notification=>{:title=>"New Comment on This is purple-air with hyphen", :path=>"/notes/admin/02-20-2019/purple-air-with-hyphen", :option=>{:body=>"Hey, @naman18996 and @jeffrey. This is Action Cable Integration Test", :icon=>"https://publiclab.org/logo.png"}}} to users:notification:13
        test/action_cable/integration/comment_notification_test.rb:98:in `test_broadcasts_when_user_is_loggedin'

 FAIL["test_no_broadcast_to_non_engaged_user", #<Minitest::Reporters::Suite:0x00005568d78a59e0 @name="CommentNotificationTest">, 136.21381672099233]
 test_no_broadcast_to_non_engaged_user#CommentNotificationTest (136.21s)
        No messages sent with {:notification=>{:title=>"New Comment on This is purple-air with hyphen", :path=>"/notes/admin/02-20-2019/purple-air-with-hyphen", :option=>{:body=>"Hey, @naman18996 and @jeffrey. This is Action Cable Integration Test", :icon=>"https://publiclab.org/logo.png"}}} to users:notification:13
        test/action_cable/integration/comment_notification_test.rb:156:in `test_no_broadcast_to_non_engaged_user'

 FAIL["test_number_of_broadcasts_when_user_is_loggedin", #<Minitest::Reporters::Suite:0x00005568d7f33d70 @name="CommentNotificationTest">, 136.40704882299178]
 test_number_of_broadcasts_when_user_is_loggedin#CommentNotificationTest (136.41s)
        No messages sent with {:notification=>{:title=>"New Comment on This is purple-air with hyphen", :path=>"/notes/admin/02-20-2019/purple-air-with-hyphen", :option=>{:body=>"Hey, @naman18996 and @jeffrey. This is Action Cable Integration Test", :icon=>"https://publiclab.org/logo.png"}}} to users:notification:13
        test/action_cable/integration/comment_notification_test.rb:128:in `test_number_of_broadcasts_when_user_is_loggedin'

ERROR["test_should_choose_i18n_for_tag/show", #<Minitest::Reporters::Suite:0x00005568d5422de8 @name="I18nTest">, 264.55822029900446]
 test_should_choose_i18n_for_tag/show#I18nTest (264.56s)
Minitest::UnexpectedError:         ArgumentError: wrong number of arguments (given 3, expected 1)
            test/integration/I18n_test.rb:416:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:411:in `each'
            test/integration/I18n_test.rb:411:in `block in <class:I18nTest>'

ERROR["test_should_choose_i18n_for_wiki/show", #<Minitest::Reporters::Suite:0x00005568d8161160 @name="I18nTest">, 319.09996690499247]
 test_should_choose_i18n_for_wiki/show#I18nTest (319.10s)
Minitest::UnexpectedError:         ArgumentError: wrong number of arguments (given 3, expected 1)
            test/integration/I18n_test.rb:360:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:355:in `each'
            test/integration/I18n_test.rb:355:in `block in <class:I18nTest>'

ERROR["test_location_with_no_user_subscribed", #<Minitest::Reporters::Suite:0x00005568de86bdb0 @name="SubscriptionLocationTest">, 325.0054426669958]
 test_location_with_no_user_subscribed#SubscriptionLocationTest (325.01s)
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: SUBSTRING_INDEX: SELECT "term_data".* FROM "term_data" WHERE (SUBSTRING_INDEX(term_data.name,':',1) = 'subscribed'         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 2),':',-1)+0 <= -10.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 3),':',-1)+0 <= 0.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 4),':',-1)+0 <= 2.4         AND SUBSTRING_INDEX(term_data.name, ':', -1) <= 80.0)
            app/models/user.rb:480:in `collect'
            app/models/user.rb:480:in `watching_location'
            test/unit/subscription_location_test.rb:38:in `block in <class:SubscriptionLocationTest>'

ERROR["test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng", #<Minitest::Reporters::Suite:0x00005568de8717b0 @name="SubscriptionLocationTest">, 325.0075888069987]
 test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng#SubscriptionLocationTest (325.01s)
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: SUBSTRING_INDEX: SELECT "term_data".* FROM "term_data" WHERE (SUBSTRING_INDEX(term_data.name,':',1) = 'subscribed'         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 2),':',-1)+0 <= 90.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 3),':',-1)+0 <= 12.7         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 4),':',-1)+0 <= 34.1         AND SUBSTRING_INDEX(term_data.name, ':', -1) <= 178.0)
            app/models/user.rb:480:in `collect'
            app/models/user.rb:480:in `watching_location'
            test/unit/subscription_location_test.rb:7:in `block in <class:SubscriptionLocationTest>'

ERROR["test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng_with_multiple_users", #<Minitest::Reporters::Suite:0x00005568de87ddf8 @name="SubscriptionLocationTest">, 325.0097785800026]
 test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng_with_multiple_users#SubscriptionLocationTest (325.01s)
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: SUBSTRING_INDEX: SELECT "term_data".* FROM "term_data" WHERE (SUBSTRING_INDEX(term_data.name,':',1) = 'subscribed'         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 2),':',-1)+0 <= 100.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 3),':',-1)+0 <= 20.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 4),':',-1)+0 <= 2.1         AND SUBSTRING_INDEX(term_data.name, ':', -1) <= 80.0)
            app/models/user.rb:480:in `collect'
            app/models/user.rb:480:in `watching_location'
            test/unit/subscription_location_test.rb:27:in `block in <class:SubscriptionLocationTest>'

ERROR["test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng_with_negative_values", #<Minitest::Reporters::Suite:0x00005568deed1c68 @name="SubscriptionLocationTest">, 325.0118371569988]
 test_return_collection_of_User_records_subscribed_to_a_area_inside_nwlat/selat/nwlng/selng_with_negative_values#SubscriptionLocationTest (325.01s)
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: SUBSTRING_INDEX: SELECT "term_data".* FROM "term_data" WHERE (SUBSTRING_INDEX(term_data.name,':',1) = 'subscribed'         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 2),':',-1)+0 <= 100.0         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 3),':',-1)+0 <= 12.7         AND SUBSTRING_INDEX(SUBSTRING_INDEX(term_data.name, ':', 4),':',-1)+0 <= 34.1         AND SUBSTRING_INDEX(term_data.name, ':', -1) <= -10.0)
            app/models/user.rb:480:in `collect'
            app/models/user.rb:480:in `watching_location'
            test/unit/subscription_location_test.rb:17:in `block in <class:SubscriptionLocationTest>'
</code>
</details>

**Comment by noi5e** [comment]
Doing some more research on these. Here's the test failing at `test/unit/api/search_service_test.rb:56`:
https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/test/unit/api/search_service_test.rb#L49-L57

If I `puts result` I get:
```
[#
<Node nid: 13, vid: 0, type: "note", language: "", title: "Blog post", uid: 2, status: 1, created: 1609810973, changed: 1609810973, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/01-04-2021/blog-post", main_image_id: nil, slug: "jeff-01-04-2021-blog-post", views: 0, latitude: 0.71e2, longitude: 0.52e2, precision: 1, flag: 0>, 

#<Node nid: 14, vid: 0, type: "redirect|13", language: "", title: "Blog post alias title", uid: 2, status: 1, created: 1609810973, changed: 1609810973, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/01-04-2021/blog-post-alias-title", main_image_id: nil, slug: "jeff-01-04-2021-blog-post-alias-title", views: 0, latitude: nil, longitude: nil, precision: nil, flag: 0>]>
```

This seems like a simple fix, just change the query to "Blog post alias title", or the assertion to expect 2 results. Will make a PR and flag here.

**Comment by noi5e** [comment]
Never mind, I closed my PR. I think the test above fails locally but passes on GitHub CI because locally I'm using SQLite, and CI is using MySQL. The test depends on a query using [Node.search](https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/app/models/node.rb#L26) that probably behaves differently depending on the environment.

I haven't looked yet, but I think the same could probably be said for these two tests which also fail locally but pass on CI:
```
FAIL["test_running_search_questions", #<Minitest::Reporters::Suite:0x00005568d703daa0 @name="SearchServiceTest">, 13.711695559992222]
test_running_search_questions#SearchServiceTest (13.71s)
Expected: 4
Actual: 3
test/unit/api/search_service_test.rb:71:in `block in class:SearchServiceTest'

FAIL["test_search_question_at_/search/questions/question", #<Minitest::Reporters::Suite:0x00005568d783ddb8 @name="SearchControllerTest">, 86.73391509799694]
test_search_question_at_/search/questions/question#SearchControllerTest (86.73s)
Expected: 8
Actual: 9
test/functional/search_controller_test.rb:51:in `block in class:SearchControllerTest'
```

That just leaves the four other tests that fail locally, which are ActionCable tests.

Also I just tried GitPod, and it seems like it's up and running like normal? Maybe I missed that announcement on chat.

**Comment by jywarren** [comment]
Also noting issues in #8177 are still present... odd...
