### ISSUE TITLE
Import French translations from Transifex

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9481]
@ebarry notes that a French translation team has been working on translations for a year (!! wow awesome!) and we'd like to import these. (cc lead French translator @XavCC)

I wanted to note steps here so we do this with good coordination:

* [ ] check what's ready to be imported (do they need reviews?)
* [ ] check what would be imported (i'm not sure we can do /only/ french translations so this might involve importing all new strings, which is OK too, just good to be clear about
* [ ] run the import, generating a new pull request with all the new translations
* [ ] add the language code (i.e. `fr`) to this line: https://github.com/publiclab/plots2/blob/main/config/application.rb#L58
* [ ] merge it!
* [ ] Check by going to https://publiclab.org/change_locale/fr
* [ ] add new languages to the footer dropdown (via the Features system, so for example `https://publiclab.org/change_locale/hi-IN` for Hindi.)

We can run through part of this checklist each time we do it.

**Comment by XavCC** [comment]
I could spend a few hours this weekend reviewing translated strings.

**Comment by jywarren** [comment]
Hi, @XavCC !! Awesome to hear from you and thank you for all the excellent work!

Just an update from our dashboard, French is 100% translated, but about 15% reviewed, but marked "ready to use":

![image](https://user-images.githubusercontent.com/24359/114200123-e2539b80-9922-11eb-800f-90bb1518ad3e.png)

So, we can download either ALL the french translations OR just those that are reviewed:

![Screen Shot 2021-04-09 at 11 01 54 AM](https://user-images.githubusercontent.com/24359/114200342-1c24a200-9923-11eb-944f-e92a6a2c4dfb.png)

I wanted to see if we could get input from the reviewers team on whether to import all or just reviewed? Either seems pretty easy!

Also i see @XavCC, OscarTrente and jibe_b are reviewers but only @XavCC seems to have a github account under that name. Happy to hear from other reviewers if that's helpful!

**Comment by jywarren** [comment]
Note /all/ translations are available in https://github.com/publiclab/plots2/pull/9482 now, so if we don't want to review first, we can just merge this and do reviews in a later import! Thanks!

**Comment by jywarren** [comment]
Interesting that we can do this in an automated way from the settings/integration dialog:

![image](https://user-images.githubusercontent.com/24359/114202003-c81abd00-9924-11eb-9943-314b41c1eee4.png)

This can be part of a new documentation of how to run imports, on https://publiclab.org/wiki/translation

**Comment by govindgoel** [comment]
@jywarren This is really awesome and now we can do it in an automated way too.

**Comment by jywarren** [comment]
OK, we'll go ahead and merge the French set for now and we can make modifications later if folks want to review more! Thank you!!!

**Comment by jywarren** [comment]
Noting a missing step - i found we need to add the language code `fr` to this line:

https://github.com/publiclab/plots2/blob/8c729b2fdd9e2428f4a9607111ecde5534c11d8e/config/application.rb#L58

**Comment by jywarren** [comment]
That worked! It should publish this coming weekend to the live site:

![image](https://user-images.githubusercontent.com/24359/114615580-dd208480-9c73-11eb-8c76-a5c4b642c828.png)

**Comment by jywarren** [comment]
Reopening as we got an error in integration tests prob from the config change...

Reverting in https://github.com/publiclab/plots2/pull/9504

https://github.com/publiclab/plots2/pull/9504/checks?check_run_id=2337234225#step:7:144

```
Minitest::UnexpectedError:         ActionView::Template::Error: missing interpolation argument :search in "Aucun résultat trouvé en cherchant \"%{search}\"" ({:tag=>"some-tag"} given)
            app/helpers/application_helper.rb:158:in `translation'
            app/views/tag/widget.html.erb:14:in `_app_views_tag_widget_html_erb__3684193017882036563_47228995284600'
            app/controllers/tag_controller.rb:250:in `widget'
            test/integration/I18n_test.rb:425:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:421:in `each'
            test/integration/I18n_test.rb:421:in `block in <class:I18nTest>'

== FAIL I18nTest#test_should_choose_i18n_for_user/_form_+_user/new (224.46s)
        <Nom d'utilisateur·ice> expected but was
        <Nom d'utilisat⋅eur·ice>..
        Expected 0 to be >= 1.
        test/integration/I18n_test.rb:198:in `block (2 levels) in <class:I18nTest>'
        test/integration/I18n_test.rb:194:in `each'
        test/integration/I18n_test.rb:194:in `block in <class:I18nTest>'
```

**Comment by XavCC** [comment]
Hi, 

I will correct this mistake in transiflex today 
```
[…]
== FAIL I18nTest#test_should_choose_i18n_for_user/_form_+_user/new (224.46s)
        <Nom d'utilisateur·ice> expected but was
        <Nom d'utilisat⋅eur·ice>..
        Expected 0 to be >= 1.
        test/integration/I18n_test.rb:198:in `block (2 levels) in <class:I18nTest>'
        test/integration/I18n_test.rb:194:in `each'
        test/integration/I18n_test.rb:194:in `block in <class:I18nTest>'
```

**Comment by jywarren** [comment]
Working on this in #9619! Next week i hope! 😅

**Comment by jywarren** [comment]
Noting we had some translation strings change, and the parameter name changed too, and there might be some things to watch out for in future attempts around parameters. Notes in https://github.com/publiclab/plots2/pull/9619#issuecomment-843583807. Hopefully it works now 🤞

**Comment by jywarren** [comment]
This is working! Great work, folks. This can now be used as a template for other language imports.

![image](https://user-images.githubusercontent.com/24359/119008699-65bfce00-b960-11eb-88e4-cc65205da0b9.png)

**Comment by jywarren** [comment]
Thanks @XavCC for your work on this!

**Comment by jywarren** [comment]
cc @imajit this is really promising for the upcoming workflows we're imagining. Take a look!

**Comment by Tlazypanda** [comment]
Hey @DalilaBA Looping you here to reach out to @XavCC for any queries you may have :sweat_smile: I am not that familiar with the transifex translation procedure so hoping this leads to some clarity :v:

**Comment by DalilaBA** [comment]
Alright thank you ☺️

**Comment by XavCC** [comment]
Hi,

Welcome @DalilaBA !

on the actual published version of the website, I tested french version.

I tried with disabled No-Script and Umatrix add-on, it works but only some few words appeared in french even only 6 words aren't translated in transiflex for french version.

By the way, I reviewed some translated strings today in transiflex french version. We reached 84% reviewed strings.

Also, I "called my twitter followers" to test french version and to send feedback 

Hope reading or hearing you soon,

Take care!

**Comment by DalilaBA** [comment]
hi @XavCC thank you 😄
I'm really new with the Transifex and the synchronization with the local files.
I just checked the fr.yml file for the ( layout._header.community ) key and it is not there, even that it is in the en.yml and translated and verified in the Transifex.
So I might think that the problem is at the synchronisation, I don't really now what to do further then that, I hope it helped
